export const initialRequiredState = {
  birthdate: '',
  city: '',
  gender: '',
  pref_gender: [],
  pref_age_min: 18,
  pref_age_max: 100,
  pref_relation_styles: [],
  is_smoker: false,
  drinks_per_month: 0,
  is_vegetarian_or_vegan: false,
  has_kids: 0,
  wants_kids_strength: 2,
  looking_for_matches: true,
  messaging_status: 'open',
  visibility: 'public',
}
export const initialOptionalState = {
  ethnicity: null,
  born_in_location: null,
  height_in_inches: null,
  has_pets: null,
  education_level: null,
  photo_urls: null,
  pinned_url: null,
  religious_belief_strength: null,
  religious_beliefs: null,
  political_beliefs: null,
}
