name: manifold

services:
  db:
    ports:
      - "${SUPABASE_DB_PORT}:${POSTGRES_PORT}"

  kong:
    ports:
      - "${KONG_PORT}:8000"
      - "8443:8443"

  studio:
    ports:
      - "3002:3000"
