export const newsContent = [
  { title: 'Armenia', slug: 'azerbaijan-offensive-halted' },
  { title: 'Canadian Sikh', slug: 'sikh-slaying-sparks-supranational-s' },
  { title: 'US 2024', slug: '2024-us-election-updates' },
  { title: 'Lost F35', slug: 'f35-lost-in-accident-in-south-carol' },
  { title: 'Aliens', slug: 'alien-bodies-unveiled-in-mexico-pro' },
  { title: 'Trump', slug: 'trump-indicted' },
  { title: 'G20', slug: 'g20-summit-in-india-bharat' },
  { title: 'Gulf Hurricane', slug: 'hurricane-lee-stengthens' },
  { title: 'Superconductor', slug: 'scientists-announce-room-temp-super' },
  { title: 'Ukraine War', slug: 'ukraine-war' },
  { title: 'Elon vs Zuck', slug: 'elon-vs-zuck' },
  { title: 'Niger coup', slug: 'niger-coup' },
  { title: 'Plane Crash', slug: 'prigozhin-feared-dead-on-plane-cras' },
  { title: 'X.com', slug: 'twitter-rebrands-to-xcom' },
]
