import * as admin from 'firebase-admin'

admin.initializeApp()

// export * from './keep-awake'
export * from './place-bet'
export * from './resolve-market'
export * from './stripe'
export * from './sell-bet'
export * from './create-contract'
export * from './create-user'
export * from './create-fold'
export * from './create-answer'
export * from './on-create-comment'
export * from './on-fold-follow'
export * from './on-fold-delete'
export * from './unsubscribe'
export * from './update-contract-metrics'
export * from './update-user-metrics'
export * from './backup-db'
export * from './change-user-info'
export * from './market-close-emails'
