"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.removecontractfromgroup = exports.updatememberrole = exports.addcontracttogroup = exports.claimdestinysub = exports.markallnotifications = exports.dividendcert = exports.swapcert = exports.validateiap = exports.updaterecommended = exports.updateloans = exports.updategroupmetrics = exports.updateusermetrics = exports.updatecontractmetrics = exports.testscheduledfunction = exports.createcomment = exports.savetwitchcredentials = exports.createpost = exports.acceptchallenge = exports.getcurrentuser = exports.createcheckoutsession = exports.stripewebhook = exports.unsubscribe = exports.closemarket = exports.resolvemarket = exports.creategroup = exports.addsubsidy = exports.createmarket = exports.claimmanalink = exports.sellshares = exports.sellbet = exports.cancelbet = exports.placebet = exports.createanswer = exports.createuser = exports.changeuserinfo = exports.transact = exports.health = exports.scheduleUpdateRecommended = exports.scheduleUpdateLoans = exports.scheduleUpdateGroupMetrics = exports.scheduleUpdateUserMetrics = exports.scheduleUpdateContractMetrics = void 0;
const admin = require("firebase-admin");
const https_1 = require("firebase-functions/v2/https");
admin.initializeApp();
// v1
__exportStar(require("./on-create-user"), exports);
__exportStar(require("./on-create-bet"), exports);
__exportStar(require("./on-create-comment-on-contract"), exports);
__exportStar(require("./on-create-comment-on-post"), exports);
var update_contract_metrics_1 = require("./update-contract-metrics");
Object.defineProperty(exports, "scheduleUpdateContractMetrics", { enumerable: true, get: function () { return update_contract_metrics_1.scheduleUpdateContractMetrics; } });
var update_user_metrics_1 = require("./update-user-metrics");
Object.defineProperty(exports, "scheduleUpdateUserMetrics", { enumerable: true, get: function () { return update_user_metrics_1.scheduleUpdateUserMetrics; } });
var update_group_metrics_1 = require("./update-group-metrics");
Object.defineProperty(exports, "scheduleUpdateGroupMetrics", { enumerable: true, get: function () { return update_group_metrics_1.scheduleUpdateGroupMetrics; } });
var update_loans_1 = require("./update-loans");
Object.defineProperty(exports, "scheduleUpdateLoans", { enumerable: true, get: function () { return update_loans_1.scheduleUpdateLoans; } });
var update_recommended_1 = require("./update-recommended");
Object.defineProperty(exports, "scheduleUpdateRecommended", { enumerable: true, get: function () { return update_recommended_1.scheduleUpdateRecommended; } });
__exportStar(require("./update-stats"), exports);
__exportStar(require("./backup-db"), exports);
__exportStar(require("./mana-signup-bonus"), exports);
__exportStar(require("./market-close-notifications"), exports);
__exportStar(require("./on-create-answer"), exports);
__exportStar(require("./on-update-contract"), exports);
__exportStar(require("./on-create-contract"), exports);
__exportStar(require("./on-follow-user"), exports);
__exportStar(require("./on-unfollow-user"), exports);
__exportStar(require("./on-create-liquidity-provision"), exports);
__exportStar(require("./on-update-group"), exports);
__exportStar(require("./on-create-txn"), exports);
__exportStar(require("./on-delete-group"), exports);
__exportStar(require("./score-contracts"), exports);
__exportStar(require("./weekly-markets-emails"), exports);
__exportStar(require("./reset-betting-streaks"), exports);
__exportStar(require("./reset-weekly-emails-flags"), exports);
__exportStar(require("./on-update-contract-follow"), exports);
__exportStar(require("./weekly-portfolio-emails"), exports);
__exportStar(require("./drizzle-liquidity"), exports);
__exportStar(require("./check-push-notification-receipts"), exports);
__exportStar(require("./on-update-reaction"), exports);
__exportStar(require("./log-writes"), exports);
__exportStar(require("./increment-streak-forgiveness"), exports);
// v2
const health_1 = require("./health");
const transact_1 = require("./transact");
const change_user_info_1 = require("./change-user-info");
const create_user_1 = require("./create-user");
const create_answer_1 = require("./create-answer");
const place_bet_1 = require("./place-bet");
const cancel_bet_1 = require("./cancel-bet");
const sell_bet_1 = require("./sell-bet");
const sell_shares_1 = require("./sell-shares");
const claim_manalink_1 = require("./claim-manalink");
const create_market_1 = require("./create-market");
const create_comment_1 = require("./create-comment");
const create_group_1 = require("./create-group");
const resolve_market_1 = require("./resolve-market");
const close_market_1 = require("./close-market");
const unsubscribe_1 = require("./unsubscribe");
const stripe_1 = require("./stripe");
const get_current_user_1 = require("./get-current-user");
const accept_challenge_1 = require("./accept-challenge");
const create_post_1 = require("./create-post");
const save_twitch_credentials_1 = require("./save-twitch-credentials");
const update_contract_metrics_2 = require("./update-contract-metrics");
const update_user_metrics_2 = require("./update-user-metrics");
const update_group_metrics_2 = require("./update-group-metrics");
const update_loans_2 = require("./update-loans");
const update_recommended_2 = require("./update-recommended");
const add_subsidy_1 = require("./add-subsidy");
const test_scheduled_function_1 = require("./test-scheduled-function");
const validate_iap_1 = require("./validate-iap");
const swap_cert_1 = require("./swap-cert");
const dividend_cert_1 = require("./dividend-cert");
const mark_all_notifications_1 = require("./mark-all-notifications");
const claim_destiny_sub_1 = require("./claim-destiny-sub");
const add_contract_to_group_1 = require("./add-contract-to-group");
const update_group_member_role_1 = require("./update-group-member-role");
const remove_contract_from_group_1 = require("./remove-contract-from-group");
const toCloudFunction = ({ opts, handler }) => {
    return (0, https_1.onRequest)(opts, handler);
};
const healthFunction = toCloudFunction(health_1.health);
exports.health = healthFunction;
const transactFunction = toCloudFunction(transact_1.transact);
exports.transact = transactFunction;
const changeUserInfoFunction = toCloudFunction(change_user_info_1.changeuserinfo);
exports.changeuserinfo = changeUserInfoFunction;
const createUserFunction = toCloudFunction(create_user_1.createuser);
exports.createuser = createUserFunction;
const createAnswerFunction = toCloudFunction(create_answer_1.createanswer);
exports.createanswer = createAnswerFunction;
const placeBetFunction = toCloudFunction(place_bet_1.placebet);
exports.placebet = placeBetFunction;
const cancelBetFunction = toCloudFunction(cancel_bet_1.cancelbet);
exports.cancelbet = cancelBetFunction;
const sellBetFunction = toCloudFunction(sell_bet_1.sellbet);
exports.sellbet = sellBetFunction;
const sellSharesFunction = toCloudFunction(sell_shares_1.sellshares);
exports.sellshares = sellSharesFunction;
const claimManalinkFunction = toCloudFunction(claim_manalink_1.claimmanalink);
exports.claimmanalink = claimManalinkFunction;
const createMarketFunction = toCloudFunction(create_market_1.createmarket);
exports.createmarket = createMarketFunction;
const addSubsidyFunction = toCloudFunction(add_subsidy_1.addsubsidy);
exports.addsubsidy = addSubsidyFunction;
const createCommentFunction = toCloudFunction(create_comment_1.createcomment);
exports.createcomment = createCommentFunction;
const createGroupFunction = toCloudFunction(create_group_1.creategroup);
exports.creategroup = createGroupFunction;
const resolveMarketFunction = toCloudFunction(resolve_market_1.resolvemarket);
exports.resolvemarket = resolveMarketFunction;
const closeMarketFunction = toCloudFunction(close_market_1.closemarket);
exports.closemarket = closeMarketFunction;
const unsubscribeFunction = toCloudFunction(unsubscribe_1.unsubscribe);
exports.unsubscribe = unsubscribeFunction;
const stripeWebhookFunction = toCloudFunction(stripe_1.stripewebhook);
exports.stripewebhook = stripeWebhookFunction;
const createCheckoutSessionFunction = toCloudFunction(stripe_1.createcheckoutsession);
exports.createcheckoutsession = createCheckoutSessionFunction;
const getCurrentUserFunction = toCloudFunction(get_current_user_1.getcurrentuser);
exports.getcurrentuser = getCurrentUserFunction;
const acceptChallenge = toCloudFunction(accept_challenge_1.acceptchallenge);
exports.acceptchallenge = acceptChallenge;
const createPostFunction = toCloudFunction(create_post_1.createpost);
exports.createpost = createPostFunction;
const saveTwitchCredentials = toCloudFunction(save_twitch_credentials_1.savetwitchcredentials);
exports.savetwitchcredentials = saveTwitchCredentials;
const testScheduledFunction = toCloudFunction(test_scheduled_function_1.testscheduledfunction);
exports.testscheduledfunction = testScheduledFunction;
const updateContractMetricsFunction = toCloudFunction(update_contract_metrics_2.updatecontractmetrics);
exports.updatecontractmetrics = updateContractMetricsFunction;
const updateUserMetricsFunction = toCloudFunction(update_user_metrics_2.updateusermetrics);
exports.updateusermetrics = updateUserMetricsFunction;
const updateGroupMetricsFunction = toCloudFunction(update_group_metrics_2.updategroupmetrics);
exports.updategroupmetrics = updateGroupMetricsFunction;
const updateLoansFunction = toCloudFunction(update_loans_2.updateloans);
exports.updateloans = updateLoansFunction;
const updateRecommendedFunction = toCloudFunction(update_recommended_2.updaterecommended);
exports.updaterecommended = updateRecommendedFunction;
const validateIAPFunction = toCloudFunction(validate_iap_1.validateiap);
exports.validateiap = validateIAPFunction;
const swapCertFunction = toCloudFunction(swap_cert_1.swapcert);
exports.swapcert = swapCertFunction;
const dividendCertFunction = toCloudFunction(dividend_cert_1.dividendcert);
exports.dividendcert = dividendCertFunction;
const markAllNotificationsFunction = toCloudFunction(mark_all_notifications_1.markallnotifications);
exports.markallnotifications = markAllNotificationsFunction;
const claimDestinySubFunction = toCloudFunction(claim_destiny_sub_1.claimdestinysub);
exports.claimdestinysub = claimDestinySubFunction;
const addContractToGroupFunction = toCloudFunction(add_contract_to_group_1.addcontracttogroup);
exports.addcontracttogroup = addContractToGroupFunction;
const updateMemberRoleFunction = toCloudFunction(update_group_member_role_1.updatememberrole);
exports.updatememberrole = updateMemberRoleFunction;
const removeContractFromGroupFunction = toCloudFunction(remove_contract_from_group_1.removecontractfromgroup);
exports.removecontractfromgroup = removeContractFromGroupFunction;
//# sourceMappingURL=index.js.map