-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS answers (
  color text,
  contract_id text,
  created_time timestamp with time zone DEFAULT now(),
  id text PRIMARY KEY DEFAULT random_alphanumeric(12) NOT NULL,
  index integer,
  is_other boolean DEFAULT false NOT NULL,
  pool_no numeric,
  pool_yes numeric,
  prob numeric,
  prob_change_day numeric DEFAULT 0,
  prob_change_month numeric DEFAULT 0,
  prob_change_week numeric DEFAULT 0,
  resolution text,
  resolution_probability numeric,
  resolution_time timestamp with time zone,
  resolver_id text,
  subsidy_pool numeric DEFAULT 0,
  text text,
  text_fts tsvector GENERATED ALWAYS AS (to_tsvector('english_extended'::regconfig, text)) STORED,
  total_liquidity numeric DEFAULT 0,
  user_id text
);



-- Row Level Security
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON answers;
CREATE POLICY "public read" ON answers FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS answer_contract_id;
CREATE INDEX answer_contract_id ON public.answers USING btree (contract_id);
DROP INDEX IF EXISTS answer_text_fts;
CREATE INDEX answer_text_fts ON public.answers USING gin (text_fts);
DROP INDEX IF EXISTS answers_pkey;
CREATE UNIQUE INDEX answers_pkey ON public.answers USING btree (id);

