-- This file is autogenerated from regen-schema.ts
create table if not exists
  audit_events (
    comment_id text,
    contract_id text,
    bet_id text,
    created_time timestamp with time zone default now() not null,
    data jsonb,
    id bigint primary key generated always as identity not null,
    name text not null,
    user_id text not null
  );

-- Row Level Security
alter table audit_events enable row level security;

-- Policies
drop policy if exists "public read" on audit_events;

create policy "public read" on audit_events for
select
  using (true);

-- Indexes
drop index if exists audit_events_pkey;

create unique index audit_events_pkey on public.audit_events using btree (id);
