-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS audit_events (
  comment_id text,
  contract_id text,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON audit_events;
CREATE POLICY "public read" ON audit_events FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS audit_events_pkey;
CREATE UNIQUE INDEX audit_events_pkey ON public.audit_events USING btree (id);

