-- This file is autogenerated from regen-schema.ts
create table if not exists
  charity_lotteries (
    lottery_num integer primary key not null,
    name text not null,
    prize_amount_usd numeric not null,
    close_time timestamp with time zone not null,
    winning_ticket_id text,
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
alter table charity_lotteries enable row level security;

-- Policies
drop policy if exists "public read" on charity_lotteries;

create policy "public read" on charity_lotteries for
select
  using (true);

-- Indexes
drop index if exists charity_lotteries_pkey;

create unique index charity_lotteries_pkey on public.charity_lotteries using btree (lottery_num);

drop index if exists charity_lotteries_close_time;

create index charity_lotteries_close_time on public.charity_lotteries using btree (close_time);
