-- This file is autogenerated from regen-schema.ts
create table if not exists
  charity_giveaways (
    giveaway_num integer primary key not null,
    name text not null,
    prize_amount_usd numeric not null,
    close_time timestamp with time zone not null,
    winning_ticket_id text,
    -- Provably fair: nonce is secret UNTIL winner is selected.
    -- Before: only share MD5(nonce) so users can record it.
    -- After: reveal nonce so users can verify MD5(nonce) matches.
    nonce text not null default encode(gen_random_bytes (32), 'hex'),
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
-- IMPORTANT: No public read policy! The nonce column is sensitive and must
-- only be exposed through the API after winner selection.
-- All access goes through the backend API which uses service role.
alter table charity_giveaways enable row level security;

-- Drop any existing public read policy
drop policy if exists "public read" on charity_giveaways;

-- Indexes
drop index if exists charity_giveaways_pkey;

create unique index charity_giveaways_pkey on public.charity_giveaways using btree (giveaway_num);

drop index if exists charity_giveaways_close_time;

create index charity_giveaways_close_time on public.charity_giveaways using btree (close_time);
