-- This file is autogenerated from regen-schema.ts
create table if not exists
  charity_giveaways (
    giveaway_num integer primary key not null,
    name text not null,
    prize_amount_usd numeric not null,
    close_time timestamp with time zone not null,
    winning_ticket_id text,
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
alter table charity_giveaways enable row level security;

-- Policies
drop policy if exists "public read" on charity_giveaways;

create policy "public read" on charity_giveaways for
select
  using (true);

-- Indexes
drop index if exists charity_giveaways_pkey;

create unique index charity_giveaways_pkey on public.charity_giveaways using btree (giveaway_num);

drop index if exists charity_giveaways_close_time;

create index charity_giveaways_close_time on public.charity_giveaways using btree (close_time);
