-- This file is autogenerated from regen-schema.ts
create table if not exists
  charity_giveaway_tickets (
    id text primary key default random_alphanumeric (12) not null,
    giveaway_num integer not null references charity_giveaways (giveaway_num),
    charity_id text not null,
    user_id text not null,
    num_tickets numeric not null,
    mana_spent numeric not null,
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
alter table charity_giveaway_tickets enable row level security;

-- No public read policy - access is through API only
-- Indexes
drop index if exists charity_giveaway_tickets_pkey;

create unique index charity_giveaway_tickets_pkey on public.charity_giveaway_tickets using btree (id);

drop index if exists charity_giveaway_tickets_giveaway_num;

create index charity_giveaway_tickets_giveaway_num on public.charity_giveaway_tickets using btree (giveaway_num);

drop index if exists charity_giveaway_tickets_giveaway_charity;

create index charity_giveaway_tickets_giveaway_charity on public.charity_giveaway_tickets using btree (giveaway_num, charity_id);

drop index if exists charity_giveaway_tickets_user_id;

create index charity_giveaway_tickets_user_id on public.charity_giveaway_tickets using btree (user_id);

drop index if exists charity_giveaway_tickets_created_time;

create index charity_giveaway_tickets_created_time on public.charity_giveaway_tickets using btree (created_time desc);
