-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS contract_liquidity (
  contract_id text NOT NULL,
  data jsonb NOT NULL,
  liquidity_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (contract_id, liquidity_id)
);



-- Row Level Security
ALTER TABLE contract_liquidity ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON contract_liquidity;
CREATE POLICY "public read" ON contract_liquidity FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS contract_liquidity_pkey;
CREATE UNIQUE INDEX contract_liquidity_pkey ON public.contract_liquidity USING btree (contract_id, liquidity_id);

