-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_perp_risk_shadow (
    contract_id text primary key,
    data jsonb not null,
    updated_time timestamp with time zone not null default now()
  );

alter table contract_perp_risk_shadow enable row level security;
