-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS contract_embeddings (
  contract_id text PRIMARY KEY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  embedding vector(1536) NOT NULL
);



-- Row Level Security
ALTER TABLE contract_embeddings ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "admin write access" ON contract_embeddings;
CREATE POLICY "admin write access" ON contract_embeddings FOR ALL TO service_role ;

DROP POLICY IF EXISTS "public read" ON contract_embeddings;
CREATE POLICY "public read" ON contract_embeddings FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS contract_embeddings_embedding_aug_2024;
CREATE INDEX contract_embeddings_embedding_aug_2024 ON public.contract_embeddings USING hnsw (embedding vector_cosine_ops);
DROP INDEX IF EXISTS contract_embeddings_pkey;
CREATE UNIQUE INDEX contract_embeddings_pkey ON public.contract_embeddings USING btree (contract_id);

