-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_perp_funding_events (
    contract_id text not null,
    ts timestamp with time zone not null,
    oracle_price numeric not null,
    pool_long_before numeric not null,
    pool_long_after numeric not null,
    pool_short_before numeric not null,
    pool_short_after numeric not null,
    funding_rate numeric not null,
    num_liquidations int not null default 0,
    adl_factor_long numeric not null default 1,
    adl_factor_short numeric not null default 1
  );

alter table contract_perp_funding_events enable row level security;

-- Indexes
drop index if exists contract_perp_funding_events_pkey;
create unique index contract_perp_funding_events_pkey on public.contract_perp_funding_events using btree (contract_id, ts);

-- Policies
drop policy if exists "public read perp funding" on contract_perp_funding_events;
create policy "public read perp funding" on contract_perp_funding_events for
select using (true);
