-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_perp_accounting_epochs (
    id bigint primary key generated by default as identity,
    contract_id text not null,
    epoch bigint not null,
    accounting_mode text not null,
    previous_mode text not null,
    oracle_price numeric,
    oracle_price_time timestamp with time zone,
    pool_long numeric not null,
    pool_short numeric not null,
    top_up_long numeric not null default 0,
    top_up_short numeric not null default 0,
    reduced_any_basis boolean not null default false,
    position_snapshot jsonb not null,
    data jsonb,
    created_time timestamp with time zone not null default now(),
    constraint contract_perp_accounting_epochs_epoch_check check (epoch > 0),
    constraint contract_perp_accounting_epochs_accounting_mode_check check (accounting_mode in ('legacy','shadow','protected')),
    constraint contract_perp_accounting_epochs_previous_mode_check check (previous_mode in ('legacy','shadow','protected'))
  );

alter table contract_perp_accounting_epochs enable row level security;

-- Indexes
drop index if exists contract_perp_accounting_epochs_contract_id_epoch_key;
create unique index contract_perp_accounting_epochs_contract_id_epoch_key on public.contract_perp_accounting_epochs using btree (contract_id, epoch);

-- Policies
drop policy if exists "public read perp accounting epochs" on contract_perp_accounting_epochs;
create policy "public read perp accounting epochs" on contract_perp_accounting_epochs for
select using (true);

-- Triggers
create trigger contract_perp_accounting_epochs_immutable before update or delete on public.contract_perp_accounting_epochs for each row execute function prevent_perp_accounting_epoch_mutation();
