-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS contract_edits (
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb NOT NULL,
  editor_id text NOT NULL,
  id serial NOT NULL,
  idempotency_key text,
  updated_keys text[]
);



-- Row Level Security
ALTER TABLE contract_edits ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON contract_edits;
CREATE POLICY "public read" ON contract_edits FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS contract_edits_contract_id_idx;
CREATE INDEX contract_edits_contract_id_idx ON public.contract_edits USING btree (contract_id);
DROP INDEX IF EXISTS contract_edits_pkey;
CREATE UNIQUE INDEX contract_edits_pkey ON public.contract_edits USING btree (id);

