-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_comment_edits (
    id integer not null,
    contract_id text not null,
    comment_id text not null,
    editor_id text not null,
    data jsonb not null,
    created_time timestamp with time zone default now() not null
  );

-- Policies
alter table contract_comment_edits enable row level security;

drop policy if exists "public read" on contract_comment_edits;

create policy "public read" on contract_comment_edits for
select
  using (true);

-- Indexes
drop index if exists contract_comment_edits_pkey;

create unique index contract_comment_edits_pkey on public.contract_comment_edits using btree (id);

drop index if exists comment_edits_comment_id_idx;

create index comment_edits_comment_id_idx on public.contract_comment_edits using btree (comment_id);
