-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_perp_positions (
    contract_id text not null,
    user_id text not null,
    direction text not null,
    size numeric not null,
    cost_basis numeric not null,
    original_cost_basis numeric not null,
    entry_price numeric not null,
    leverage numeric not null,
    liquidation_price numeric not null,
    opened_time timestamp with time zone not null default now(),
    updated_time timestamp with time zone not null default now(),
    constraint contract_perp_positions_direction_check check (direction in ('long','short'))
  );

alter table contract_perp_positions enable row level security;

-- Indexes
drop index if exists contract_perp_positions_pkey;
create unique index contract_perp_positions_pkey on public.contract_perp_positions using btree (contract_id, user_id, direction);

drop index if exists contract_perp_positions_contract_dir;
create index contract_perp_positions_contract_dir on public.contract_perp_positions using btree (contract_id, direction);

drop index if exists contract_perp_positions_user;
create index contract_perp_positions_user on public.contract_perp_positions using btree (user_id);

-- One-way mode: at most one (contract, user) row with size > 0.
drop index if exists contract_perp_positions_one_way;
create unique index contract_perp_positions_one_way on public.contract_perp_positions using btree (contract_id, user_id) where size > 0;

-- Policies
drop policy if exists "public read perp positions" on contract_perp_positions;
create policy "public read perp positions" on contract_perp_positions for
select using (true);
