-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_liquidity (
    contract_id text not null,
    data jsonb not null,
    liquidity_id text not null,
    constraint primary key (contract_id, liquidity_id)
  );

-- Row Level Security
alter table contract_liquidity enable row level security;

-- Policies
drop policy if exists "public read" on contract_liquidity;

create policy "public read" on contract_liquidity for
select
  using (true);

-- Indexes
drop index if exists contract_liquidity_pkey;

create unique index contract_liquidity_pkey on public.contract_liquidity using btree (contract_id, liquidity_id);
