-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS contract_comment_edits (
  comment_id text NOT NULL,
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb NOT NULL,
  editor_id text NOT NULL,
  id serial NOT NULL
);



-- Row Level Security
ALTER TABLE contract_comment_edits ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON contract_comment_edits;
CREATE POLICY "public read" ON contract_comment_edits FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS comment_edits_comment_id_idx;
CREATE INDEX comment_edits_comment_id_idx ON public.contract_comment_edits USING btree (comment_id);
DROP INDEX IF EXISTS contract_comment_edits_pkey;
CREATE UNIQUE INDEX contract_comment_edits_pkey ON public.contract_comment_edits USING btree (id);

