-- This file is autogenerated from regen-schema.ts
create table if not exists
  contract_perp_pool_events (
    applied_ts timestamp with time zone not null default statement_timestamp(),
    cash_in numeric not null default 0,
    cash_out numeric not null default 0,
    contract_id text not null,
    data jsonb,
    event_type text not null,
    id bigserial primary key,
    oracle_price numeric,
    oracle_ts timestamp with time zone,
    pool_long_after numeric not null,
    pool_long_before numeric not null,
    pool_short_after numeric not null,
    pool_short_before numeric not null,
    constraint contract_perp_pool_events_cash_in_check check (cash_in >= 0),
    constraint contract_perp_pool_events_cash_out_check check (cash_out >= 0),
    constraint contract_perp_pool_events_event_type_check check (
      event_type in (
        'baseline',
        'create',
        'open',
        'add',
        'flip',
        'close',
        'subsidy',
        'oracle',
        'funding',
        'resolve'
      )
    ),
    constraint contract_perp_pool_events_oracle_price_check check (
      (
        (oracle_price is null)
        or (oracle_price > (0)::numeric)
      )
    ),
    constraint contract_perp_pool_events_pool_cash_balance_check check (
      (
        abs(
          (
            (
              ((pool_long_before + pool_short_before) + cash_in) - cash_out
            ) - pool_long_after
          ) - pool_short_after
        ) <= 0.001
      )
    ),
    constraint contract_perp_pool_events_pool_long_after_check check (pool_long_after >= 0),
    constraint contract_perp_pool_events_pool_long_before_check check (pool_long_before >= 0),
    constraint contract_perp_pool_events_pool_short_after_check check (pool_short_after >= 0),
    constraint contract_perp_pool_events_pool_short_before_check check (pool_short_before >= 0)
  );

-- Triggers
create trigger contract_perp_pool_events_immutable before
update
or delete on public.contract_perp_pool_events for each row
execute function prevent_perp_pool_event_mutation ();

-- Functions
create
or replace function public.prevent_perp_pool_event_mutation () returns trigger language plpgsql as $function$
begin
  if tg_op = 'UPDATE' and new is not distinct from old then
    return old;
  end if;
  raise exception 'PERP pool events are append-only (event %)', old.id;
end
$function$;

-- Row Level Security
alter table contract_perp_pool_events enable row level security;

-- Policies
drop policy if exists "public read perp pool events" on contract_perp_pool_events;

create policy "public read perp pool events" on contract_perp_pool_events for
select
  using (true);

-- Indexes
drop index if exists contract_perp_pool_events_pkey;

create unique index contract_perp_pool_events_pkey on public.contract_perp_pool_events using btree (id);

drop index if exists contract_perp_pool_events_applied;

create index contract_perp_pool_events_applied on public.contract_perp_pool_events using btree (applied_ts, contract_id);

drop index if exists contract_perp_pool_events_contract_applied;

create index contract_perp_pool_events_contract_applied on public.contract_perp_pool_events using btree (contract_id, applied_ts desc, id desc);
