-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS contract_comments (
  comment_id text NOT NULL,
  contract_id text NOT NULL,
  created_time timestamp with time zone NOT NULL,
  data jsonb NOT NULL,
  dislikes integer DEFAULT 0,
  likes integer DEFAULT 0 NOT NULL,
  user_id text NOT NULL,
  visibility text,
  CONSTRAINT PRIMARY KEY (contract_id, comment_id)
);


-- Triggers
CREATE TRIGGER comment_populate BEFORE INSERT OR UPDATE ON public.contract_comments FOR EACH ROW EXECUTE FUNCTION comment_populate_cols();

-- Functions
CREATE OR REPLACE FUNCTION public.comment_populate_cols()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$ begin 
    if new.data is not null then new.visibility := (new.data)->>'visibility';
    new.user_id := (new.data)->>'userId';
    new.created_time := case
  when new.data ? 'createdTime' then millis_to_ts(((new.data)->>'createdTime')::bigint)
  else null
  end;
    end if;
    return new;
end $function$
;

-- Row Level Security
ALTER TABLE contract_comments ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON contract_comments;
CREATE POLICY "public read" ON contract_comments FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS contract_comments_contract_id_created_time_idx;
CREATE INDEX contract_comments_contract_id_created_time_idx ON public.contract_comments USING btree (contract_id, created_time DESC);
DROP INDEX IF EXISTS contract_comments_created_time_idx;
CREATE INDEX contract_comments_created_time_idx ON public.contract_comments USING btree (created_time DESC);
DROP INDEX IF EXISTS contract_comments_id;
CREATE INDEX contract_comments_id ON public.contract_comments USING btree (comment_id);
DROP INDEX IF EXISTS contract_comments_pkey;
CREATE UNIQUE INDEX contract_comments_pkey ON public.contract_comments USING btree (contract_id, comment_id);
DROP INDEX IF EXISTS contract_replies;
CREATE INDEX contract_replies ON public.contract_comments USING btree (((data ->> 'replyToCommentId'::text)), contract_id, created_time DESC);
DROP INDEX IF EXISTS contracts_comments_user_id;
CREATE INDEX contracts_comments_user_id ON public.contract_comments USING btree (user_id, created_time);

