-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS creator_portfolio_history (
  fees_earned numeric NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  ts timestamp without time zone DEFAULT now() NOT NULL,
  unique_bettors integer NOT NULL,
  user_id text NOT NULL,
  views integer NOT NULL,
  volume numeric NOT NULL
);



-- Row Level Security
ALTER TABLE creator_portfolio_history ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON creator_portfolio_history;
CREATE POLICY "public read" ON creator_portfolio_history FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS creator_portfolio_history_pkey;
CREATE UNIQUE INDEX creator_portfolio_history_pkey ON public.creator_portfolio_history USING btree (id);
DROP INDEX IF EXISTS creator_portfolio_history_user_ts;
CREATE INDEX creator_portfolio_history_user_ts ON public.creator_portfolio_history USING btree (user_id, ts DESC);

