-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS daily_stats (
  activation numeric,
  active_d1_to_d3 numeric,
  avg_user_actions numeric,
  bet_amount numeric,
  bet_count numeric,
  cash_bet_amount numeric,
  comment_count numeric,
  contract_count numeric,
  d1 numeric,
  d1_bet_3_day_average numeric,
  d1_bet_average numeric,
  dau numeric,
  engaged_users numeric,
  feed_conversion numeric,
  m1 numeric,
  mau numeric,
  nd1 numeric,
  nw1 numeric,
  sales numeric,
  signups numeric,
  signups_real numeric,
  start_date date PRIMARY KEY NOT NULL,
  topic_daus jsonb,
  w1 numeric,
  wau numeric
);



-- Row Level Security
ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON daily_stats;
CREATE POLICY "public read" ON daily_stats FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS daily_stats_pkey;
CREATE UNIQUE INDEX daily_stats_pkey ON public.daily_stats USING btree (start_date);

