-- This file is autogenerated from regen-schema.ts
create table if not exists
  daily_stats (
    start_date date not null,
    dau numeric,
    wau numeric,
    mau numeric,
    avg_user_actions numeric,
    sales numeric,
    engaged_users numeric,
    d1 numeric,
    nd1 numeric,
    nw1 numeric,
    active_d1_to_d3 numeric,
    bet_count numeric,
    contract_count numeric,
    comment_count numeric,
    signups numeric,
    signups_real numeric,
    w1 numeric,
    m1 numeric,
    activation numeric,
    bet_amount numeric,
    d1_bet_average numeric,
    d1_bet_3_day_average numeric,
    feed_conversion numeric
  );

-- Policies
alter table daily_stats enable row level security;

drop policy if exists "public read" on daily_stats;

create policy "public read" on daily_stats for
select
  using (true);

-- Indexes
drop index if exists daily_stats_pkey;

create unique index daily_stats_pkey on public.daily_stats using btree (start_date);
