-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS dashboard_groups (
  dashboard_id text NOT NULL,
  group_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (dashboard_id, group_id)
);

-- Foreign Keys
ALTER TABLE dashboard_groups ADD CONSTRAINT dashboard_groups_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES dashboards(id);
ALTER TABLE dashboard_groups ADD CONSTRAINT public_dashboard_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Row Level Security
ALTER TABLE dashboard_groups ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "Enable read access for admin" ON dashboard_groups;
CREATE POLICY "Enable read access for admin" ON dashboard_groups FOR SELECT TO service_role USING (true) ;

-- Indexes
DROP INDEX IF EXISTS dashboard_groups_pkey;
CREATE UNIQUE INDEX dashboard_groups_pkey ON public.dashboard_groups USING btree (dashboard_id, group_id);

