-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS dashboard_follows (
  created_time timestamp with time zone DEFAULT now(),
  dashboard_id text NOT NULL,
  follower_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (dashboard_id, follower_id)
);



-- Indexes
DROP INDEX IF EXISTS dashboard_follows_pkey;
CREATE UNIQUE INDEX dashboard_follows_pkey ON public.dashboard_follows USING btree (dashboard_id, follower_id);
DROP INDEX IF EXISTS idx_dashboard_follows_follower_dashboard;
CREATE INDEX idx_dashboard_follows_follower_dashboard ON public.dashboard_follows USING btree (follower_id, dashboard_id);

