-- This file is autogenerated from regen-schema.ts
create table if not exists
  delete_after_reading (
    created_time timestamp with time zone default now() not null,
    data jsonb,
    id bigint primary key generated always as identity not null,
    user_id text not null
  );

-- Foreign Keys
alter table delete_after_reading
add constraint delete_after_reading_user_id_fkey foreign key (user_id) references users (id);

-- Row Level Security
alter table delete_after_reading enable row level security;

-- Indexes
drop index if exists delete_after_reading_pkey;

create unique index delete_after_reading_pkey on public.delete_after_reading using btree (id);
