-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS delete_after_reading (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);

-- Foreign Keys
ALTER TABLE delete_after_reading ADD CONSTRAINT delete_after_reading_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);


-- Row Level Security
ALTER TABLE delete_after_reading ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS delete_after_reading_pkey;
CREATE UNIQUE INDEX delete_after_reading_pkey ON public.delete_after_reading USING btree (id);

