-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS discord_messages_markets (
  channel_id text NOT NULL,
  last_updated_thread_time bigint,
  market_id text NOT NULL,
  market_slug text NOT NULL,
  message_id text PRIMARY KEY NOT NULL,
  thread_id text
);



-- Row Level Security
ALTER TABLE discord_messages_markets ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS discord_messages_markets_pkey;
CREATE UNIQUE INDEX discord_messages_markets_pkey ON public.discord_messages_markets USING btree (message_id);

