-- This file is autogenerated from regen-schema.ts
create table if not exists
  discord_messages_markets (
    message_id text not null,
    market_id text not null,
    market_slug text not null,
    channel_id text not null,
    last_updated_thread_time bigint,
    thread_id text
  );

-- Indexes
drop index if exists discord_messages_markets_pkey;

create unique index discord_messages_markets_pkey on public.discord_messages_markets using btree (message_id);
