-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS discord_users (
  api_key text NOT NULL,
  discord_user_id text PRIMARY KEY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE discord_users ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS discord_users_pkey;
CREATE UNIQUE INDEX discord_users_pkey ON public.discord_users USING btree (discord_user_id);

