-- This file is autogenerated from regen-schema.ts
create table if not exists
  discord_users (
    api_key text not null,
    discord_user_id text primary key not null,
    user_id text not null
  );

-- Row Level Security
alter table discord_users enable row level security;

-- Indexes
drop index if exists discord_users_pkey;

create unique index discord_users_pkey on public.discord_users using btree (discord_user_id);
