-- This file is autogenerated from regen-schema.ts
create table if not exists
  gidx_receipts (
    id bigint primary key generated always as identity,
    user_id text,
    merchant_transaction_id text not null,
    session_id text not null,
    created_time timestamp with time zone default now() not null,
    status text,
    status_code integer,
    payment_status_code text,
    payment_status_message text,
    transaction_status_code text,
    transaction_status_message text,
    merchant_session_id text,
    amount numeric(20, 2),
    currency text,
    payment_method_type text,
    payment_amount_type text,
    session_score integer,
    reason_codes text[],
    service_type text,
    txn_id text,
    payment_data jsonb,
    callback_data jsonb
  );

-- Foreign Keys
alter table gidx_receipts
add constraint gidx_receipts_user_id_fkey foreign key (user_id) references users (id);

-- Row Level Security
alter table gidx_receipts enable row level security;

-- Indexes
drop index if exists cash_out_receipts_user_id_idx;

create index cash_out_receipts_user_id_idx on public.gidx_receipts using btree (user_id);

drop index if exists cash_out_receipts_merchant_transaction_id_idx;

create index cash_out_receipts_merchant_transaction_id_idx on public.gidx_receipts using btree (merchant_transaction_id);
