-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS gidx_receipts (
  amount numeric(20,2),
  callback_data jsonb,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  currency text,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_session_id text,
  merchant_transaction_id text NOT NULL,
  payment_amount_type text,
  payment_data jsonb,
  payment_method_type text,
  payment_status_code text,
  payment_status_message text,
  reason_codes text[],
  service_type text,
  session_id text NOT NULL,
  session_score integer,
  status text,
  status_code integer,
  transaction_status_code text,
  transaction_status_message text,
  txn_id text,
  user_id text
);

-- Foreign Keys
ALTER TABLE gidx_receipts ADD CONSTRAINT gidx_receipts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);


-- Row Level Security
ALTER TABLE gidx_receipts ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS cash_out_receipts_merchant_transaction_id_idx;
CREATE INDEX cash_out_receipts_merchant_transaction_id_idx ON public.gidx_receipts USING btree (merchant_transaction_id);
DROP INDEX IF EXISTS cash_out_receipts_user_id_idx;
CREATE INDEX cash_out_receipts_user_id_idx ON public.gidx_receipts USING btree (user_id);
DROP INDEX IF EXISTS gidx_receipts_pkey;
CREATE UNIQUE INDEX gidx_receipts_pkey ON public.gidx_receipts USING btree (id);

