-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS group_embeddings (
  created_time timestamp without time zone DEFAULT now() NOT NULL,
  embedding vector(1536) NOT NULL,
  group_id text PRIMARY KEY NOT NULL
);

-- Foreign Keys
ALTER TABLE group_embeddings ADD CONSTRAINT public_group_embeddings_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Row Level Security
ALTER TABLE group_embeddings ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "admin write access" ON group_embeddings;
CREATE POLICY "admin write access" ON group_embeddings FOR ALL TO service_role ;

DROP POLICY IF EXISTS "public read" ON group_embeddings;
CREATE POLICY "public read" ON group_embeddings FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS group_embeddings_pkey;
CREATE UNIQUE INDEX group_embeddings_pkey ON public.group_embeddings USING btree (group_id);

