-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS group_contracts (
  contract_id text NOT NULL,
  group_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (group_id, contract_id)
);

-- Foreign Keys
ALTER TABLE group_contracts ADD CONSTRAINT group_contracts_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON UPDATE CASCADE;


-- Row Level Security
ALTER TABLE group_contracts ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "Enable read access for bets on markets user can access" ON group_contracts;
CREATE POLICY "Enable read access for bets on markets user can access" ON group_contracts FOR SELECT USING ((EXISTS ( SELECT 1
   FROM groups
  WHERE (groups.id = group_contracts.group_id)))) ;

-- Indexes
DROP INDEX IF EXISTS group_contracts_contract_id;
CREATE INDEX group_contracts_contract_id ON public.group_contracts USING btree (contract_id);
DROP INDEX IF EXISTS group_contracts_pkey;
CREATE UNIQUE INDEX group_contracts_pkey ON public.group_contracts USING btree (group_id, contract_id);

