-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS group_groups (
  bottom_id text NOT NULL,
  top_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (top_id, bottom_id)
);

-- Foreign Keys
ALTER TABLE group_groups ADD CONSTRAINT group_groups_bottom_id_fkey FOREIGN KEY (bottom_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE group_groups ADD CONSTRAINT group_groups_top_id_fkey FOREIGN KEY (top_id) REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Row Level Security
ALTER TABLE group_groups ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON group_groups;
CREATE POLICY "public read" ON group_groups FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS group_groups_top_id_bottom_id_pkey;
CREATE UNIQUE INDEX group_groups_top_id_bottom_id_pkey ON public.group_groups USING btree (top_id, bottom_id);

