-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS groups (
  about jsonb,
  banner_url text,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text,
  id text PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
  importance_score numeric DEFAULT 0,
  name text NOT NULL,
  name_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, name)) STORED,
  privacy_status text,
  slug text NOT NULL,
  total_members numeric DEFAULT 0
);



-- Row Level Security
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON groups;
CREATE POLICY "public read" ON groups FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS group_slug;
CREATE INDEX group_slug ON public.groups USING btree (slug);
DROP INDEX IF EXISTS groups_pkey;
CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);
DROP INDEX IF EXISTS privacy_status_idx;
CREATE INDEX privacy_status_idx ON public.groups USING btree (privacy_status);
DROP INDEX IF EXISTS total_members;
CREATE INDEX total_members ON public.groups USING btree (total_members DESC);

