-- This file is autogenerated from regen-schema.ts
create table if not exists
  instances (
    created_time timestamp with time zone default now() not null,
    id text primary key default uuid_generate_v4 () not null,
    name text not null,
    owner_id text not null references users (id),
    schema_name text not null,
    status text default 'active'::text not null,
    subdomain text not null
  );

-- Row Level Security
alter table instances enable row level security;

-- Policies
drop policy if exists "public read" on instances;

create policy "public read" on instances for
select
  using (true);

-- Indexes
drop index if exists instances_owner_id_idx;

create index instances_owner_id_idx on public.instances using btree (owner_id);

drop index if exists instances_schema_name_idx;

create unique index instances_schema_name_idx on public.instances using btree (schema_name);

drop index if exists instances_subdomain_idx;

create unique index instances_subdomain_idx on public.instances using btree (subdomain);
