-- This file is autogenerated from regen-schema.ts
create table if not exists
  kyc_bonus_rewards (
    claim_time timestamp with time zone,
    claimed boolean default false,
    created_time timestamp with time zone default now(),
    reward_amount numeric not null,
    user_id text primary key not null
  );

-- Foreign Keys
alter table kyc_bonus_rewards
add constraint kyc_bonus_rewards_user_id_fkey foreign key (user_id) references users (id);

-- Row Level Security
alter table kyc_bonus_rewards enable row level security;

-- Policies
drop policy if exists "public read" on kyc_bonus_rewards;

create policy "public read" on kyc_bonus_rewards for
select
  using (true);

-- Indexes
drop index if exists kyc_bonus_rewards_pkey;

create unique index kyc_bonus_rewards_pkey on public.kyc_bonus_rewards using btree (user_id);
