-- This file is autogenerated from regen-schema.ts
create table if not exists
  kyc_bonus_rewards (
    user_id text not null,
    reward_amount numeric not null,
    created_time timestamp with time zone default now(),
    claimed boolean default false
  );

-- Foreign Keys
alter table kyc_bonus_rewards
add constraint kyc_bonus_rewards_user_id_fkey foreign key (user_id) references users (id);

-- Indexes
drop index if exists kyc_bonus_rewards_pkey;

create unique index kyc_bonus_rewards_pkey on public.kyc_bonus_rewards using btree (user_id);
