-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS kyc_bonus_rewards (
  claim_time timestamp with time zone,
  claimed boolean DEFAULT false,
  created_time timestamp with time zone DEFAULT now(),
  reward_amount numeric NOT NULL,
  user_id text PRIMARY KEY NOT NULL
);

-- Foreign Keys
ALTER TABLE kyc_bonus_rewards ADD CONSTRAINT kyc_bonus_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);


-- Row Level Security
ALTER TABLE kyc_bonus_rewards ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON kyc_bonus_rewards;
CREATE POLICY "public read" ON kyc_bonus_rewards FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS kyc_bonus_rewards_pkey;
CREATE UNIQUE INDEX kyc_bonus_rewards_pkey ON public.kyc_bonus_rewards USING btree (user_id);

