-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS league_chats (
  channel_id text NOT NULL,
  cohort text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  division integer NOT NULL,
  id serial NOT NULL,
  owner_id text,
  season integer NOT NULL
);



-- Row Level Security
ALTER TABLE league_chats ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON league_chats;
CREATE POLICY "public read" ON league_chats FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS league_chats_pkey;
CREATE UNIQUE INDEX league_chats_pkey ON public.league_chats USING btree (id);
DROP INDEX IF EXISTS league_chats_season_division_cohort_key;
CREATE UNIQUE INDEX league_chats_season_division_cohort_key ON public.league_chats USING btree (season, division, cohort);

