-- This file is autogenerated from regen-schema.ts
create table if not exists
  league_chats (
    id integer not null,
    channel_id text not null,
    created_time timestamp with time zone default now() not null,
    season integer not null,
    division integer not null,
    cohort text not null,
    owner_id text
  );

-- Policies
alter table league_chats enable row level security;

drop policy if exists "public read" on league_chats;

create policy "public read" on league_chats for
select
  using (true);

-- Indexes
drop index if exists league_chats_pkey;

create unique index league_chats_pkey on public.league_chats using btree (id);

drop index if exists league_chats_season_division_cohort_key;

create unique index league_chats_season_division_cohort_key on public.league_chats using btree (season, division, cohort);
