-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS leagues (
  cohort text NOT NULL,
  created_time timestamp without time zone DEFAULT now() NOT NULL,
  division integer NOT NULL,
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  mana_earned numeric DEFAULT 0.0 NOT NULL,
  mana_earned_breakdown jsonb DEFAULT '{}'::jsonb NOT NULL,
  rank_snapshot integer,
  season integer NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE leagues ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON leagues;
CREATE POLICY "public read" ON leagues FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS leagues_pkey;
CREATE UNIQUE INDEX leagues_pkey ON public.leagues USING btree (id);
DROP INDEX IF EXISTS unique_user_id_season;
CREATE UNIQUE INDEX unique_user_id_season ON public.leagues USING btree (user_id, season);

