-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_waitlist (
    id bigint not null,
    email text not null,
    created_time timestamp with time zone default now() not null
  );

-- Policies
alter table love_waitlist enable row level security;

drop policy if exists "anon insert" on love_waitlist;

create policy "anon insert" on love_waitlist for insert
with
  check (true);

-- Indexes
drop index if exists love_waitlist_pkey;

create unique index love_waitlist_pkey on public.love_waitlist using btree (id);
