-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS love_waitlist (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  email text NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL
);



-- Row Level Security
ALTER TABLE love_waitlist ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "anon insert" ON love_waitlist;
CREATE POLICY "anon insert" ON love_waitlist FOR INSERT WITH CHECK (true);

-- Indexes
DROP INDEX IF EXISTS love_waitlist_pkey;
CREATE UNIQUE INDEX love_waitlist_pkey ON public.love_waitlist USING btree (id);

