-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS love_stars (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text NOT NULL,
  star_id text DEFAULT random_alphanumeric(12) NOT NULL,
  target_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (creator_id, star_id)
);



-- Row Level Security
ALTER TABLE love_stars ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON love_stars;
CREATE POLICY "public read" ON love_stars FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS love_stars_pkey;
CREATE UNIQUE INDEX love_stars_pkey ON public.love_stars USING btree (creator_id, star_id);

