-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS love_likes (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text NOT NULL,
  like_id text DEFAULT random_alphanumeric(12) NOT NULL,
  target_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (creator_id, like_id)
);



-- Row Level Security
ALTER TABLE love_likes ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON love_likes;
CREATE POLICY "public read" ON love_likes FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS love_likes_pkey;
CREATE UNIQUE INDEX love_likes_pkey ON public.love_likes USING btree (creator_id, like_id);
DROP INDEX IF EXISTS user_likes_target_id_raw;
CREATE INDEX user_likes_target_id_raw ON public.love_likes USING btree (target_id);

