-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS love_questions (
  answer_type text DEFAULT 'free_response'::text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  importance_score numeric DEFAULT 0 NOT NULL,
  multiple_choice_options jsonb,
  question text NOT NULL
);



-- Row Level Security
ALTER TABLE love_questions ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON love_questions;
CREATE POLICY "public read" ON love_questions FOR ALL USING (true) ;

-- Indexes
DROP INDEX IF EXISTS love_questions_pkey;
CREATE UNIQUE INDEX love_questions_pkey ON public.love_questions USING btree (id);

