-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS lover_comments (
  content jsonb NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  hidden boolean DEFAULT false NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  on_user_id text NOT NULL,
  reply_to_comment_id bigint,
  user_avatar_url text NOT NULL,
  user_id text NOT NULL,
  user_name text NOT NULL,
  user_username text NOT NULL
);



-- Row Level Security
ALTER TABLE lover_comments ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON lover_comments;
CREATE POLICY "public read" ON lover_comments FOR ALL USING (true) ;

-- Indexes
DROP INDEX IF EXISTS lover_comments_pkey;
CREATE UNIQUE INDEX lover_comments_pkey ON public.lover_comments USING btree (id);
DROP INDEX IF EXISTS lover_comments_user_id_idx;
CREATE INDEX lover_comments_user_id_idx ON public.lover_comments USING btree (on_user_id);

