-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS lovers (
  age integer DEFAULT 18 NOT NULL,
  bio json,
  born_in_location text,
  city text NOT NULL,
  city_latitude numeric(9,6),
  city_longitude numeric(9,6),
  comments_enabled boolean DEFAULT true NOT NULL,
  company text,
  country text,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  drinks_per_month integer,
  education_level text,
  ethnicity text[],
  gender text NOT NULL,
  geodb_city_id text,
  has_kids integer,
  height_in_inches integer,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  is_smoker boolean,
  is_vegetarian_or_vegan boolean,
  last_online_time timestamp with time zone DEFAULT now() NOT NULL,
  looking_for_matches boolean DEFAULT true NOT NULL,
  messaging_status text DEFAULT 'open'::text NOT NULL,
  occupation text,
  occupation_title text,
  photo_urls text[],
  pinned_url text,
  political_beliefs text[],
  pref_age_max integer DEFAULT 100 NOT NULL,
  pref_age_min integer DEFAULT 18 NOT NULL,
  pref_gender text[] NOT NULL,
  pref_relation_styles text[] NOT NULL,
  referred_by_username text,
  region_code text,
  religious_belief_strength integer,
  religious_beliefs text,
  twitter text,
  university text,
  user_id text NOT NULL,
  visibility text DEFAULT 'public'::text NOT NULL,
  wants_kids_strength integer DEFAULT 0 NOT NULL,
  website text
);



-- Row Level Security
ALTER TABLE lovers ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON lovers;
CREATE POLICY "public read" ON lovers FOR SELECT USING (true) ;

DROP POLICY IF EXISTS "self update" ON lovers;
CREATE POLICY "self update" ON lovers FOR UPDATE WITH CHECK ((user_id = firebase_uid()));

-- Indexes
DROP INDEX IF EXISTS lovers_pkey;
CREATE UNIQUE INDEX lovers_pkey ON public.lovers USING btree (id);
DROP INDEX IF EXISTS lovers_user_id_idx;
CREATE INDEX lovers_user_id_idx ON public.lovers USING btree (user_id);
DROP INDEX IF EXISTS unique_user_id;
CREATE UNIQUE INDEX unique_user_id ON public.lovers USING btree (user_id);

