-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_questions (
    id bigint not null,
    creator_id text not null,
    created_time timestamp with time zone default now() not null,
    question text not null,
    importance_score numeric default 0 not null,
    answer_type text default 'free_response'::text not null,
    multiple_choice_options jsonb
  );

-- Policies
alter table love_questions enable row level security;

drop policy if exists "public read" on love_questions;

create policy "public read" on love_questions for all using (true);

-- Indexes
drop index if exists love_questions_pkey;

create unique index love_questions_pkey on public.love_questions using btree (id);
