-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS manachan_tweets (
  cost numeric,
  created_time numeric,
  id text PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
  tweet text,
  tweet_id text,
  user_id text,
  username text
);



-- Row Level Security
ALTER TABLE manachan_tweets ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON manachan_tweets;
CREATE POLICY "Enable read access for all users" ON manachan_tweets FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS manachan_tweets_pkey;
CREATE UNIQUE INDEX manachan_tweets_pkey ON public.manachan_tweets USING btree (id);

