-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS manalinks (
  amount numeric NOT NULL,
  created_time timestamp with time zone DEFAULT now(),
  creator_id text NOT NULL,
  expires_time timestamp with time zone,
  id text PRIMARY KEY DEFAULT random_alphanumeric(8) NOT NULL,
  max_uses numeric,
  message text
);



-- Row Level Security
ALTER TABLE manalinks ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "Enable read access for admin" ON manalinks;
CREATE POLICY "Enable read access for admin" ON manalinks FOR SELECT TO service_role USING (true) ;

-- Indexes
DROP INDEX IF EXISTS manalinks_creator_id;
CREATE INDEX manalinks_creator_id ON public.manalinks USING btree (creator_id);
DROP INDEX IF EXISTS manalinks_pkey;
CREATE UNIQUE INDEX manalinks_pkey ON public.manalinks USING btree (id);

