-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS manalink_claims (
  manalink_id text NOT NULL,
  txn_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (manalink_id, txn_id)
);



-- Row Level Security
ALTER TABLE manalink_claims ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON manalink_claims;
CREATE POLICY "public read" ON manalink_claims FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS manalink_claims_pkey;
CREATE UNIQUE INDEX manalink_claims_pkey ON public.manalink_claims USING btree (manalink_id, txn_id);

