-- This file is autogenerated from regen-schema.ts
create table if not exists
  manalinks (
    amount numeric not null,
    created_time timestamp with time zone default now(),
    creator_id text not null,
    expires_time timestamp with time zone,
    id text primary key default random_alphanumeric (8) not null,
    max_uses numeric,
    message text
  );

-- Row Level Security
alter table manalinks enable row level security;

-- Policies
drop policy if exists "Enable read access for admin" on manalinks;

create policy "Enable read access for admin" on manalinks for
select
  to service_role using (true);

-- Indexes
drop index if exists manalinks_creator_id;

create index manalinks_creator_id on public.manalinks using btree (creator_id);

drop index if exists manalinks_pkey;

create unique index manalinks_pkey on public.manalinks using btree (id);
