-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS market_ads (
  cost_per_view numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  embedding vector(1536) NOT NULL,
  funds numeric NOT NULL,
  id text PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
  market_id text NOT NULL,
  user_id text NOT NULL
);

-- Foreign Keys
ALTER TABLE market_ads ADD CONSTRAINT market_ads_market_id_fkey FOREIGN KEY (market_id) REFERENCES contracts(id);


-- Row Level Security
ALTER TABLE market_ads ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "admin write access" ON market_ads;
CREATE POLICY "admin write access" ON market_ads FOR ALL TO service_role ;

DROP POLICY IF EXISTS "public read" ON market_ads;
CREATE POLICY "public read" ON market_ads FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS market_ad_cost;
CREATE INDEX market_ad_cost ON public.market_ads USING btree (cost_per_view DESC);
DROP INDEX IF EXISTS market_ads_pkey;
CREATE UNIQUE INDEX market_ads_pkey ON public.market_ads USING btree (id);

