-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS mod_reports (
  comment_id text NOT NULL,
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  mod_note text,
  report_id serial NOT NULL,
  status status_type DEFAULT 'new'::status_type NOT NULL,
  user_id text NOT NULL
);



-- Indexes
DROP INDEX IF EXISTS mod_reports_pkey;
CREATE UNIQUE INDEX mod_reports_pkey ON public.mod_reports USING btree (report_id);

