-- This file is autogenerated from regen-schema.ts
create table if not exists
  mod_reports (
    comment_id text not null,
    contract_id text not null,
    created_time timestamp with time zone default now() not null,
    mod_note text,
    report_id serial not null,
    status status_type default 'new'::status_type not null,
    user_id text not null
  );

-- Indexes
drop index if exists mod_reports_pkey;

create unique index mod_reports_pkey on public.mod_reports using btree (report_id);

drop index if exists mod_status;

create index mod_status on mod_reports (status);