-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS news (
  author text,
  contract_ids text[],
  created_time timestamp without time zone DEFAULT now() NOT NULL,
  description text,
  group_ids text[],
  id serial NOT NULL,
  image_url text,
  published_time timestamp without time zone NOT NULL,
  source_id text,
  source_name text,
  title text NOT NULL,
  title_embedding vector(1536) NOT NULL,
  url text NOT NULL
);



-- Row Level Security
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON news;
CREATE POLICY "public read" ON news FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS news_pkey;
CREATE UNIQUE INDEX news_pkey ON public.news USING btree (id);

