-- This file is autogenerated from regen-schema.ts
create table if not exists
  news (
    author text,
    contract_ids text[],
    created_time timestamp without time zone default now() not null,
    description text,
    group_ids text[],
    id serial not null,
    image_url text,
    published_time timestamp without time zone not null,
    source_id text,
    source_name text,
    title text not null,
    title_embedding vector (1536) not null,
    url text not null
  );

-- Row Level Security
alter table news enable row level security;

-- Policies
drop policy if exists "public read" on news;

create policy "public read" on news for
select
  using (true);

-- Indexes
drop index if exists news_pkey;

create unique index news_pkey on public.news using btree (id);
