-- This file is autogenerated from regen-schema.ts
create table if not exists
  news (
    id integer not null,
    created_time timestamp without time zone default now() not null,
    title text not null,
    url text not null,
    published_time timestamp without time zone not null,
    author text,
    description text,
    image_url text,
    source_id text,
    source_name text,
    title_embedding vector (1536) not null,
    contract_ids text[],
    group_ids text[]
  );

-- Policies
alter table news enable row level security;

drop policy if exists "public read" on news;

create policy "public read" on news for
select
  using (true);

-- Indexes
drop index if exists news_pkey;

create unique index news_pkey on public.news using btree (id);
