-- This file is autogenerated from regen-schema.ts
create table if not exists
  old_post_comments (
    comment_id text default uuid_generate_v4 () not null,
    created_time timestamp with time zone default now(),
    data jsonb not null,
    fs_updated_time timestamp without time zone,
    post_id text not null,
    user_id text,
    primary key (post_id, comment_id)
  );

-- Row Level Security
alter table old_post_comments enable row level security;

-- Policies
drop policy if exists "public read" on old_post_comments;

create policy "public read" on old_post_comments for
select
  using (true);

-- Indexes
drop index if exists post_comments_pkey;

create unique index post_comments_pkey on public.old_post_comments using btree (post_id, comment_id);
