-- This file is autogenerated from regen-schema.ts
create table if not exists
  oracle_prices (
    feed_id text not null,
    ts timestamp with time zone not null,
    price numeric not null
  );

alter table oracle_prices enable row level security;

-- Indexes
drop index if exists oracle_prices_pkey;
create unique index oracle_prices_pkey on public.oracle_prices using btree (feed_id, ts);

drop index if exists oracle_prices_feed_ts_desc;
create index oracle_prices_feed_ts_desc on public.oracle_prices using btree (feed_id, ts desc);

-- Policies
drop policy if exists "public read oracle_prices" on oracle_prices;
create policy "public read oracle_prices" on oracle_prices for
select using (true);
