-- This file is autogenerated from regen-schema.ts
create table if not exists
  pending_answers (
    id text primary key default random_alphanumeric (12) not null,
    contract_id text not null,
    user_id text not null,
    text text not null,
    created_time timestamp with time zone default now() not null,
    status text default 'pending' not null,
    reviewed_by text,
    reviewed_time timestamp with time zone
  );

-- Foreign Keys
alter table pending_answers
add constraint pending_answers_contract_id_fkey foreign key (contract_id) references contracts (id);

-- Row Level Security
alter table pending_answers enable row level security;

-- Policies
drop policy if exists "public read" on pending_answers;

create policy "public read" on pending_answers for
select
  using (true);

-- Indexes
drop index if exists pending_answers_pkey;

create unique index pending_answers_pkey on public.pending_answers using btree (id);

drop index if exists pending_answers_contract_id_idx;

create index pending_answers_contract_id_idx on public.pending_answers using btree (contract_id);

drop index if exists pending_answers_user_id_idx;

create index pending_answers_user_id_idx on public.pending_answers using btree (user_id);

drop index if exists pending_answers_pending_idx;

create index pending_answers_pending_idx on public.pending_answers using btree (contract_id, created_time)
where
  status = 'pending';
