-- This file is autogenerated from regen-schema.ts
create table if not exists
  perp_suggestion_votes (
    suggestion_id bigint not null,
    user_id text not null,
    created_time timestamp with time zone not null default now(),
    constraint perp_suggestion_votes_pkey primary key (suggestion_id, user_id),
    constraint perp_suggestion_votes_suggestion_id_fkey foreign key (suggestion_id) references perp_suggestions (id) on delete cascade
  );

alter table perp_suggestion_votes enable row level security;
