-- This file is autogenerated from regen-schema.ts
create table if not exists
  perp_suggestions (
    id bigserial primary key,
    user_id text not null,
    name text not null,
    data_source text,
    hidden boolean not null default false,
    created_time timestamp with time zone not null default now()
  );

alter table perp_suggestions enable row level security;

-- Indexes
drop index if exists perp_suggestions_name_key;
create unique index perp_suggestions_name_key on public.perp_suggestions using btree (lower(name));

drop index if exists perp_suggestions_user_created;
create index perp_suggestions_user_created on public.perp_suggestions using btree (user_id, created_time desc);
