-- This file is autogenerated from regen-schema.ts
create table if not exists
  platform_calibration (
    created_time timestamp with time zone default now() not null,
    data jsonb not null,
    id bigint primary key generated always as identity not null
  );

-- Row Level Security
alter table platform_calibration enable row level security;

-- Policies
drop policy if exists "public read" on platform_calibration;

create policy "public read" on platform_calibration for
select
  using (true);

-- Indexes
drop index if exists platform_calibration_pkey;

create unique index platform_calibration_pkey on public.platform_calibration using btree (id);
