-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS platform_calibration (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL
);



-- Row Level Security
ALTER TABLE platform_calibration ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON platform_calibration;
CREATE POLICY "public read" ON platform_calibration FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS platform_calibration_pkey;
CREATE UNIQUE INDEX platform_calibration_pkey ON public.platform_calibration USING btree (id);

