-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS portfolios (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text NOT NULL,
  id text PRIMARY KEY NOT NULL,
  items jsonb NOT NULL,
  name text NOT NULL,
  slug text NOT NULL
);



-- Row Level Security
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON portfolios;
CREATE POLICY "public read" ON portfolios FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS portfolios_pkey;
CREATE UNIQUE INDEX portfolios_pkey ON public.portfolios USING btree (id);

