-- This file is autogenerated from regen-schema.ts
create table if not exists
  portfolios (
    created_time timestamp with time zone default now() not null,
    creator_id text not null,
    id text primary key not null,
    items jsonb not null,
    name text not null,
    slug text not null
  );

-- Row Level Security
alter table portfolios enable row level security;

-- Policies
drop policy if exists "public read" on portfolios;

create policy "public read" on portfolios for
select
  using (true);

-- Indexes
drop index if exists portfolios_pkey;

create unique index portfolios_pkey on public.portfolios using btree (id);
