-- This file is autogenerated from regen-schema.ts
create table if not exists
  post_follows (
    post_id text not null,
    created_time timestamp with time zone default now() not null,
    user_id text not null,
    primary key (post_id, user_id)
  );

-- Row Level Security
alter table post_follows enable row level security;

-- Policies
drop policy if exists "public read" on post_follows;

create policy "public read" on post_follows for
select
  using (true);

-- Indexes
drop index if exists post_follows_idx;

create index post_follows_idx on public.post_follows using btree (user_id);
