-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS posts (
  bet_id text,
  contract_comment_id text,
  contract_id text,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_avatar_url text NOT NULL,
  user_id text NOT NULL,
  user_name text NOT NULL,
  user_username text NOT NULL
);



-- Row Level Security
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON posts;
CREATE POLICY "public read" ON posts FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS posts_pkey1;
CREATE UNIQUE INDEX posts_pkey1 ON public.posts USING btree (id);
DROP INDEX IF EXISTS reposts_contract;
CREATE INDEX reposts_contract ON public.posts USING btree (contract_id);
DROP INDEX IF EXISTS reposts_contract_comment;
CREATE INDEX reposts_contract_comment ON public.posts USING btree (contract_comment_id);
DROP INDEX IF EXISTS reposts_user;
CREATE INDEX reposts_user ON public.posts USING btree (user_id);

