-- This file is autogenerated from regen-schema.ts
create table if not exists
  post_comment_edits (
    comment_id text not null,
    post_id text not null,
    created_time timestamp with time zone default now() not null,
    data jsonb not null,
    editor_id text not null,
    id bigint generated always as identity
  );

-- Row Level Security
alter table post_comment_edits enable row level security;

-- Policies
drop policy if exists "public read" on post_comment_edits;

create policy "public read" on post_comment_edits for
select
  using (true);

-- Indexes
drop index if exists post_comment_edits_comment_id_idx;

create index post_comment_edits_comment_id_idx on public.post_comment_edits using btree (comment_id);
