-- This file is autogenerated from regen-schema.ts
create table if not exists
  predictle_daily (
    created_time timestamp with time zone default now(),
    data jsonb not null,
    date_pt text primary key not null
  );

-- Indexes
drop index if exists predictle_daily_pkey;

create unique index predictle_daily_pkey on public.predictle_daily using btree (date_pt);
