-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_message_channels (
    created_time timestamp with time zone default now() not null,
    id bigint primary key generated always as identity not null,
    last_updated_time timestamp with time zone default now() not null,
    title text
  );

-- Row Level Security
alter table private_user_message_channels enable row level security;

-- Policies
drop policy if exists "public read" on private_user_message_channels;

create policy "public read" on private_user_message_channels for all using (true);

-- Indexes
drop index if exists private_user_message_channels_pkey;

create unique index private_user_message_channels_pkey on public.private_user_message_channels using btree (id);
