-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_phone_numbers (
    created_time timestamp with time zone default now() not null,
    id bigint primary key generated always as identity not null,
    last_updated_time timestamp with time zone default now() not null,
    phone_number text not null,
    user_id text not null
  );

-- Row Level Security
alter table private_user_phone_numbers enable row level security;

-- Indexes
drop index if exists private_user_phone_numbers_pkey;

create unique index private_user_phone_numbers_pkey on public.private_user_phone_numbers using btree (id);

drop index if exists unique_phone_number_user_id;

create unique index unique_phone_number_user_id on public.private_user_phone_numbers using btree (user_id);

drop index if exists unique_user_phone_number;

create unique index unique_user_phone_number on public.private_user_phone_numbers using btree (phone_number);
