-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS private_user_seen_message_channels (
  channel_id bigint NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE private_user_seen_message_channels ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "private member insert" ON private_user_seen_message_channels;
CREATE POLICY "private member insert" ON private_user_seen_message_channels FOR INSERT WITH CHECK (((firebase_uid() IS NOT NULL) AND can_access_private_messages(channel_id, firebase_uid())));

DROP POLICY IF EXISTS "private member read" ON private_user_seen_message_channels;
CREATE POLICY "private member read" ON private_user_seen_message_channels FOR SELECT USING (((firebase_uid() IS NOT NULL) AND can_access_private_messages(channel_id, firebase_uid()))) ;

-- Indexes
DROP INDEX IF EXISTS private_user_seen_message_channels_pkey;
CREATE UNIQUE INDEX private_user_seen_message_channels_pkey ON public.private_user_seen_message_channels USING btree (id);
DROP INDEX IF EXISTS user_seen_private_messages_created_time_desc_idx;
CREATE INDEX user_seen_private_messages_created_time_desc_idx ON public.private_user_seen_message_channels USING btree (user_id, channel_id, created_time DESC);

