-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS private_user_message_channels (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  last_updated_time timestamp with time zone DEFAULT now() NOT NULL,
  title text
);



-- Row Level Security
ALTER TABLE private_user_message_channels ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON private_user_message_channels;
CREATE POLICY "public read" ON private_user_message_channels FOR ALL USING (true) ;

-- Indexes
DROP INDEX IF EXISTS private_user_message_channels_pkey;
CREATE UNIQUE INDEX private_user_message_channels_pkey ON public.private_user_message_channels USING btree (id);

