-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS private_users (
  data jsonb NOT NULL,
  id text PRIMARY KEY NOT NULL,
  weekly_portfolio_email_sent boolean DEFAULT false,
  weekly_trending_email_sent boolean DEFAULT false
);



-- Row Level Security
ALTER TABLE private_users ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "private read" ON private_users;
CREATE POLICY "private read" ON private_users FOR SELECT USING ((firebase_uid() = id)) ;

-- Indexes
DROP INDEX IF EXISTS private_users_data_api_key;
CREATE INDEX private_users_data_api_key ON public.private_users USING btree (((data ->> 'apiKey'::text)));
DROP INDEX IF EXISTS private_users_pkey;
CREATE UNIQUE INDEX private_users_pkey ON public.private_users USING btree (id);

