-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_message_channel_members (
    id bigint not null,
    created_time timestamp with time zone default now() not null,
    channel_id bigint not null,
    user_id text not null,
    role text default 'member'::text not null,
    status text default 'proposed'::text not null,
    notify_after_time timestamp with time zone default now() not null
  );

-- Policies
alter table private_user_message_channel_members enable row level security;

drop policy if exists "private read" on private_user_message_channel_members;

create policy "private read" on private_user_message_channel_members for
select
  using (
    (
      (firebase_uid () is not null)
      and can_access_private_messages (channel_id, firebase_uid ())
    )
  );

-- Indexes
drop index if exists private_user_message_channel_members_pkey;

create unique index private_user_message_channel_members_pkey on public.private_user_message_channel_members using btree (id);

drop index if exists unique_user_channel;

create unique index unique_user_channel on public.private_user_message_channel_members using btree (channel_id, user_id);

drop index if exists pumcm_members_idx;

create index pumcm_members_idx on public.private_user_message_channel_members using btree (channel_id, user_id);
