-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_users (
    data jsonb not null,
    id text primary key not null,
    weekly_portfolio_email_sent boolean default false,
    weekly_trending_email_sent boolean default false
  );

-- Row Level Security
alter table private_users enable row level security;

-- Policies
drop policy if exists "private read" on private_users;

create policy "private read" on private_users for
select
  using ((firebase_uid () = id));

-- Indexes
drop index if exists private_users_data_api_key;

create index private_users_data_api_key on public.private_users using btree (((data ->> 'apiKey'::text)));

drop index if exists private_users_pkey;

create unique index private_users_pkey on public.private_users using btree (id);
