-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS private_user_messages (
  channel_id bigint NOT NULL,
  content jsonb NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL,
  visibility text DEFAULT 'private'::text NOT NULL
);



-- Row Level Security
ALTER TABLE private_user_messages ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS private_user_messages_channel_id_idx;
CREATE INDEX private_user_messages_channel_id_idx ON public.private_user_messages USING btree (channel_id, created_time DESC);
DROP INDEX IF EXISTS private_user_messages_pkey;
CREATE UNIQUE INDEX private_user_messages_pkey ON public.private_user_messages USING btree (id);

