-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_messages (
    id bigint not null,
    channel_id bigint not null,
    user_id text not null,
    content jsonb not null,
    created_time timestamp with time zone default now() not null,
    visibility text default 'private'::text not null
  );

-- Indexes
drop index if exists private_user_messages_pkey;

create unique index private_user_messages_pkey on public.private_user_messages using btree (id);

drop index if exists private_user_messages_channel_id_idx;

create index private_user_messages_channel_id_idx on public.private_user_messages using btree (channel_id, created_time desc);
