-- This file is autogenerated from regen-schema.ts
create table if not exists
  push_notification_tickets (
    id text not null,
    status text not null,
    user_id text not null,
    notification_id text not null,
    created_time timestamp with time zone default now() not null,
    receipt_status text not null,
    receipt_error text
  );

-- Indexes
drop index if exists push_notification_tickets_pkey;

create unique index push_notification_tickets_pkey on public.push_notification_tickets using btree (id);

drop index if exists push_notification_tickets_status;

create index push_notification_tickets_status on public.push_notification_tickets using btree (receipt_status);
