-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS push_notification_tickets (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id text PRIMARY KEY NOT NULL,
  notification_id text NOT NULL,
  receipt_error text,
  receipt_status text NOT NULL,
  status text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE push_notification_tickets ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS push_notification_tickets_pkey;
CREATE UNIQUE INDEX push_notification_tickets_pkey ON public.push_notification_tickets USING btree (id);
DROP INDEX IF EXISTS push_notification_tickets_status;
CREATE INDEX push_notification_tickets_status ON public.push_notification_tickets USING btree (receipt_status);

