-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS q_and_a (
  bounty numeric NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  deleted boolean DEFAULT false NOT NULL,
  description text NOT NULL,
  id text PRIMARY KEY NOT NULL,
  question text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE q_and_a ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON q_and_a;
CREATE POLICY "public read" ON q_and_a FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS q_and_a_pkey;
CREATE UNIQUE INDEX q_and_a_pkey ON public.q_and_a USING btree (id);

