-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS q_and_a_answers (
  award numeric DEFAULT 0.0 NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  deleted boolean DEFAULT false NOT NULL,
  id text PRIMARY KEY NOT NULL,
  q_and_a_id text NOT NULL,
  text text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE q_and_a_answers ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON q_and_a_answers;
CREATE POLICY "public read" ON q_and_a_answers FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS q_and_a_answers_pkey;
CREATE UNIQUE INDEX q_and_a_answers_pkey ON public.q_and_a_answers USING btree (id);

