-- This file is autogenerated from regen-schema.ts
create table if not exists
  q_and_a (
    bounty numeric not null,
    created_time timestamp with time zone default now() not null,
    deleted boolean default false not null,
    description text not null,
    id text primary key not null,
    question text not null,
    user_id text not null
  );

-- Row Level Security
alter table q_and_a enable row level security;

-- Policies
drop policy if exists "public read" on q_and_a;

create policy "public read" on q_and_a for
select
  using (true);

-- Indexes
drop index if exists q_and_a_pkey;

create unique index q_and_a_pkey on public.q_and_a using btree (id);
