-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS redemption_status (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  session_id text NOT NULL,
  status text NOT NULL,
  transaction_id text NOT NULL,
  txn_id text NOT NULL,
  user_id text NOT NULL
);

-- Foreign Keys
ALTER TABLE redemption_status ADD CONSTRAINT redemption_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);


-- Row Level Security
ALTER TABLE redemption_status ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS redemption_status_pkey;
CREATE UNIQUE INDEX redemption_status_pkey ON public.redemption_status USING btree (id);

