-- This file is autogenerated from regen-schema.ts
create table if not exists
  reports (
    content_id text not null,
    content_owner_id text not null,
    content_type text not null,
    created_time timestamp with time zone default now(),
    description text,
    id text default uuid_generate_v4 () not null,
    parent_id text,
    parent_type text,
    user_id text not null,
    dismissed_by_user_id text
  );

-- Foreign Keys
alter table reports
add constraint reports_content_owner_id_fkey foreign key (content_owner_id) references users (id);

alter table reports
add constraint reports_user_id_fkey foreign key (user_id) references users (id);
