-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS reports (
  content_id text NOT NULL,
  content_owner_id text NOT NULL,
  content_type text NOT NULL,
  created_time timestamp with time zone DEFAULT now(),
  description text,
  id text DEFAULT uuid_generate_v4() NOT NULL,
  parent_id text,
  parent_type text,
  user_id text NOT NULL
);

-- Foreign Keys
ALTER TABLE reports ADD CONSTRAINT reports_content_owner_id_fkey FOREIGN KEY (content_owner_id) REFERENCES users(id);
ALTER TABLE reports ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);



