-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS reviews (
  content jsonb,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  market_id text NOT NULL,
  rating numeric NOT NULL,
  reviewer_id text NOT NULL,
  vendor_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (reviewer_id, market_id)
);



-- Indexes
DROP INDEX IF EXISTS reviews_pkey;
CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (reviewer_id, market_id);

