-- This file is autogenerated from regen-schema.ts
create table if not exists
  scheduler_info (
    created_time timestamp with time zone default now() not null,
    id bigint primary key generated always as identity not null,
    job_name text not null,
    last_end_time timestamp with time zone,
    last_start_time timestamp with time zone
  );

-- Row Level Security
alter table scheduler_info enable row level security;

-- Policies
drop policy if exists "public read" on scheduler_info;

create policy "public read" on scheduler_info for all using (true);

-- Indexes
drop index if exists scheduler_info_job_name_key;

create unique index scheduler_info_job_name_key on public.scheduler_info using btree (job_name);

drop index if exists scheduler_info_pkey;

create unique index scheduler_info_pkey on public.scheduler_info using btree (id);
