-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS scheduler_info (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  job_name text NOT NULL,
  last_end_time timestamp with time zone,
  last_start_time timestamp with time zone
);



-- Row Level Security
ALTER TABLE scheduler_info ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON scheduler_info;
CREATE POLICY "public read" ON scheduler_info FOR ALL USING (true) ;

-- Indexes
DROP INDEX IF EXISTS scheduler_info_job_name_key;
CREATE UNIQUE INDEX scheduler_info_job_name_key ON public.scheduler_info USING btree (job_name);
DROP INDEX IF EXISTS scheduler_info_pkey;
CREATE UNIQUE INDEX scheduler_info_pkey ON public.scheduler_info USING btree (id);

