-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS sent_emails (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  email_template_id text NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE sent_emails ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS one_time_emails_user_id;
CREATE INDEX one_time_emails_user_id ON public.sent_emails USING btree (user_id, email_template_id);
DROP INDEX IF EXISTS sent_emails_pkey;
CREATE UNIQUE INDEX sent_emails_pkey ON public.sent_emails USING btree (id);

