-- This file is autogenerated from regen-schema.ts
create table if not exists
  sent_emails (
    id bigint not null,
    user_id text not null,
    email_template_id text not null,
    created_time timestamp with time zone default now() not null
  );

-- Indexes
drop index if exists sent_emails_pkey;

create unique index sent_emails_pkey on public.sent_emails using btree (id);

drop index if exists one_time_emails_user_id;

create index one_time_emails_user_id on public.sent_emails using btree (user_id, email_template_id);
