-- This file is autogenerated from regen-schema.ts
create table if not exists
  sent_emails (
    created_time timestamp with time zone default now() not null,
    email_template_id text not null,
    id bigint primary key generated always as identity not null,
    user_id text not null
  );

-- Row Level Security
alter table sent_emails enable row level security;

-- Indexes
drop index if exists one_time_emails_user_id;

create index one_time_emails_user_id on public.sent_emails using btree (user_id, email_template_id);

drop index if exists sent_emails_pkey;

create unique index sent_emails_pkey on public.sent_emails using btree (id);
