-- This file is autogenerated from regen-schema.ts
create table if not exists
  shop_orders (
    created_time timestamp with time zone default now() not null,
    delivered_time timestamp with time zone,
    id uuid primary key default gen_random_uuid () not null,
    item_id text not null,
    metadata jsonb,
    price_mana bigint not null,
    printful_order_id text,
    printful_status text,
    quantity integer default 1 not null,
    shipped_time timestamp with time zone,
    status text default 'CREATED'::text not null,
    txn_id text,
    user_id text not null
  );

-- Indexes
drop index if exists shop_orders_pkey;

create unique index shop_orders_pkey on public.shop_orders using btree (id);
