-- This file is autogenerated from regen-schema.ts
create table if not exists
  stats (
    daily_values numeric[],
    title text primary key not null
  );

-- Row Level Security
alter table stats enable row level security;

-- Policies
drop policy if exists "public read" on stats;

create policy "public read" on stats for
select
  using (true);

-- Indexes
drop index if exists stats_pkey;

create unique index stats_pkey on public.stats using btree (title);
