-- This file is autogenerated from regen-schema.ts
create table if not exists
  stats (title text not null, daily_values numeric[]);

-- Policies
alter table stats enable row level security;

drop policy if exists "public read" on stats;

create policy "public read" on stats for
select
  using (true);

-- Indexes
drop index if exists stats_pkey;

create unique index stats_pkey on public.stats using btree (title);
