-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS stats (
  daily_values numeric[],
  title text PRIMARY KEY NOT NULL
);



-- Row Level Security
ALTER TABLE stats ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON stats;
CREATE POLICY "public read" ON stats FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS stats_pkey;
CREATE UNIQUE INDEX stats_pkey ON public.stats USING btree (title);

