-- This file is autogenerated from regen-schema.ts
create table if not exists
  stonk_images (
    contract_id text primary key not null,
    image_url text not null
  );

-- Row Level Security
alter table stonk_images enable row level security;

-- Indexes
drop index if exists stonk_images_pkey;

create unique index stonk_images_pkey on public.stonk_images using btree (contract_id);
