-- This file is autogenerated from regen-schema.ts
create table if not exists
  sweepstakes (
    sweepstakes_num integer primary key not null,
    name text not null,
    prizes jsonb not null, -- [{rank: 1, amountUsdc: 1000, label: "1st"}, {rankStart: 4, rankEnd: 10, amountUsdc: 50, label: "4th-10th"}]
    close_time timestamp with time zone not null,
    winning_ticket_ids text[], -- Array of winner ticket IDs in rank order
    -- Provably fair: nonce is secret UNTIL winners are selected.
    -- Before: only share MD5(nonce) so users can record it.
    -- After: reveal nonce so users can verify MD5(nonce) matches.
    nonce text not null default encode(gen_random_bytes (32), 'hex'),
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
-- IMPORTANT: No public read policy! The nonce column is sensitive and must
-- only be exposed through the API after winner selection.
-- All access goes through the backend API which uses service role.
alter table sweepstakes enable row level security;

-- Drop any existing public read policy
drop policy if exists "public read" on sweepstakes;

-- Indexes
drop index if exists sweepstakes_pkey;

create unique index sweepstakes_pkey on public.sweepstakes using btree (sweepstakes_num);

drop index if exists sweepstakes_close_time;

create index sweepstakes_close_time on public.sweepstakes using btree (close_time);
