-- This file is autogenerated from regen-schema.ts
create table if not exists
  sweepstakes_free_tickets (
    sweepstakes_num integer not null references sweepstakes (sweepstakes_num),
    user_id text not null,
    claimed_time timestamp with time zone default now() not null,
    primary key (sweepstakes_num, user_id)
  );

-- Row Level Security
alter table sweepstakes_free_tickets enable row level security;

-- No public read policy - access is through API only
-- Indexes (primary key creates its own index)
drop index if exists sweepstakes_free_tickets_user_id;

create index sweepstakes_free_tickets_user_id on public.sweepstakes_free_tickets using btree (user_id);
