-- This file is autogenerated from regen-schema.ts
create table if not exists
  sweepstakes_tickets (
    id text primary key default random_alphanumeric (12) not null,
    sweepstakes_num integer not null references sweepstakes (sweepstakes_num),
    user_id text not null,
    num_tickets numeric not null,
    mana_spent numeric not null,
    is_free boolean default false not null,
    created_time timestamp with time zone default now() not null
  );

-- Row Level Security
alter table sweepstakes_tickets enable row level security;

-- No public read policy - access is through API only
-- Indexes
drop index if exists sweepstakes_tickets_pkey;

create unique index sweepstakes_tickets_pkey on public.sweepstakes_tickets using btree (id);

drop index if exists sweepstakes_tickets_sweepstakes_num;

create index sweepstakes_tickets_sweepstakes_num on public.sweepstakes_tickets using btree (sweepstakes_num);

drop index if exists sweepstakes_tickets_user_id;

create index sweepstakes_tickets_user_id on public.sweepstakes_tickets using btree (user_id);

drop index if exists sweepstakes_tickets_sweepstakes_user;

create index sweepstakes_tickets_sweepstakes_user on public.sweepstakes_tickets using btree (sweepstakes_num, user_id);

drop index if exists sweepstakes_tickets_created_time;

create index sweepstakes_tickets_created_time on public.sweepstakes_tickets using btree (created_time desc);
