-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS system_trading_status (
  status boolean NOT NULL,
  token text PRIMARY KEY NOT NULL
);



-- Row Level Security
ALTER TABLE system_trading_status ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON system_trading_status;
CREATE POLICY "public read" ON system_trading_status FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS system_trading_status_pkey;
CREATE UNIQUE INDEX system_trading_status_pkey ON public.system_trading_status USING btree (token);

