-- This file is autogenerated from regen-schema.ts
create table if not exists
  system_trading_status (
    status boolean not null,
    token text primary key not null
  );

-- Row Level Security
alter table system_trading_status enable row level security;

-- Policies
drop policy if exists "public read" on system_trading_status;

create policy "public read" on system_trading_status for
select
  using (true);

-- Indexes
drop index if exists system_trading_status_pkey;

create unique index system_trading_status_pkey on public.system_trading_status using btree (token);
