-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS topic_embeddings (
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  embedding vector(1536) NOT NULL,
  topic text PRIMARY KEY NOT NULL
);



-- Row Level Security
ALTER TABLE topic_embeddings ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "admin write access" ON topic_embeddings;
CREATE POLICY "admin write access" ON topic_embeddings FOR ALL TO service_role ;

DROP POLICY IF EXISTS "public read" ON topic_embeddings;
CREATE POLICY "public read" ON topic_embeddings FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS topic_embeddings_pkey;
CREATE UNIQUE INDEX topic_embeddings_pkey ON public.topic_embeddings USING btree (topic);

