-- This file is autogenerated from regen-schema.ts
create table if not exists
  topic_embeddings (
    created_at timestamp without time zone default now() not null,
    embedding vector (1536) not null,
    topic text primary key not null
  );

-- Row Level Security
alter table topic_embeddings enable row level security;

-- Policies
drop policy if exists "admin write access" on topic_embeddings;

create policy "admin write access" on topic_embeddings for all to service_role;

drop policy if exists "public read" on topic_embeddings;

create policy "public read" on topic_embeddings for
select
  using (true);

-- Indexes
drop index if exists topic_embeddings_pkey;

create unique index topic_embeddings_pkey on public.topic_embeddings using btree (topic);
