-- This file is autogenerated from regen-schema.ts
create table if not exists
  tv_schedule (
    contract_id text not null,
    creator_id text not null,
    end_time timestamp with time zone not null,
    id serial not null,
    is_featured boolean default false,
    schedule_created_time timestamp with time zone default now(),
    source text not null,
    start_time timestamp with time zone not null,
    stream_id text not null,
    title text not null
  );

-- Indexes
drop index if exists tv_schedule_pkey;

create unique index tv_schedule_pkey on public.tv_schedule using btree (id);

alter table tv_schedule enable row level security;

-- Policies
drop policy if exists "public read" on tv_schedule;

create policy "public read" on tv_schedule for
    select
    using (true);

