-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS txn_summary_stats (
  category text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  end_time timestamp with time zone NOT NULL,
  from_type text NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  quest_type text,
  start_time timestamp with time zone NOT NULL,
  to_type text NOT NULL,
  token text NOT NULL,
  total_amount numeric NOT NULL
);



-- Row Level Security
ALTER TABLE txn_summary_stats ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON txn_summary_stats;
CREATE POLICY "public read" ON txn_summary_stats FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS txn_summary_stats_pkey;
CREATE UNIQUE INDEX txn_summary_stats_pkey ON public.txn_summary_stats USING btree (id);

