-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS txns (
  amount numeric NOT NULL,
  category text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb NOT NULL,
  from_id text NOT NULL,
  from_type text NOT NULL,
  id text PRIMARY KEY DEFAULT random_alphanumeric(8) NOT NULL,
  to_id text NOT NULL,
  to_type text NOT NULL,
  token text DEFAULT 'M$'::text NOT NULL CONSTRAINT txns_token_check CHECK ((token = ANY (ARRAY['M$'::text, 'CASH'::text, 'SHARE'::text, 'SPICE'::text])))
);



-- Row Level Security
ALTER TABLE txns ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON txns;
CREATE POLICY "public read" ON txns FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS txns_category_native;
CREATE INDEX txns_category_native ON public.txns USING btree (category);
DROP INDEX IF EXISTS txns_category_to_id;
CREATE INDEX txns_category_to_id ON public.txns USING btree (category, to_id);
DROP INDEX IF EXISTS txns_category_to_id_from_id;
CREATE INDEX txns_category_to_id_from_id ON public.txns USING btree (category, to_id, from_id);
DROP INDEX IF EXISTS txns_from_created_time;
CREATE INDEX txns_from_created_time ON public.txns USING btree (from_id, created_time);
DROP INDEX IF EXISTS txns_pkey;
CREATE UNIQUE INDEX txns_pkey ON public.txns USING btree (id);
DROP INDEX IF EXISTS txns_to_created_time;
CREATE INDEX txns_to_created_time ON public.txns USING btree (to_id, created_time);

