-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_seen_chats (
  channel_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_seen_chats ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_seen_chats;
CREATE POLICY "public read" ON user_seen_chats FOR SELECT USING (true) ;

DROP POLICY IF EXISTS "user can insert" ON user_seen_chats;
CREATE POLICY "user can insert" ON user_seen_chats FOR INSERT WITH CHECK (true);

-- Indexes
DROP INDEX IF EXISTS user_seen_chats_created_time_desc_idx;
CREATE INDEX user_seen_chats_created_time_desc_idx ON public.user_seen_chats USING btree (user_id, channel_id, created_time DESC);
DROP INDEX IF EXISTS user_seen_chats_pkey;
CREATE UNIQUE INDEX user_seen_chats_pkey ON public.user_seen_chats USING btree (id);

