-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_seen_chats (
    channel_id text not null,
    created_time timestamp with time zone default now() not null,
    id bigint primary key generated always as identity not null,
    user_id text not null
  );

-- Row Level Security
alter table user_seen_chats enable row level security;

-- Policies
drop policy if exists "public read" on user_seen_chats;

create policy "public read" on user_seen_chats for
select
  using (true);

drop policy if exists "user can insert" on user_seen_chats;

create policy "user can insert" on user_seen_chats for insert
with
  check (true);

-- Indexes
drop index if exists user_seen_chats_created_time_desc_idx;

create index user_seen_chats_created_time_desc_idx on public.user_seen_chats using btree (user_id, channel_id, created_time desc);

drop index if exists user_seen_chats_pkey;

create unique index user_seen_chats_pkey on public.user_seen_chats using btree (id);
