-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_notifications (
    user_id text not null,
    notification_id text not null,
    data jsonb not null
  );

-- Policies
alter table user_notifications enable row level security;

drop policy if exists "public read" on user_notifications;

create policy "public read" on user_notifications for
select
  using (true);

-- Indexes
drop index if exists user_notifications_pkey;

create unique index user_notifications_pkey on public.user_notifications using btree (user_id, notification_id);

drop index if exists user_notifications_notification_id;

create index user_notifications_notification_id on public.user_notifications using btree (notification_id, user_id);

drop index if exists user_notifications_user_id_created_time;

create index user_notifications_user_id_created_time on public.user_notifications using btree (
  user_id,
  (((data -> 'createdTime'::text))::bigint) desc
);
