-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_portfolio_history_latest (
    user_id text not null,
    ts timestamp without time zone not null,
    investment_value numeric not null,
    balance numeric not null,
    total_deposits numeric not null,
    loan_total numeric,
    spice_balance numeric default 0.0 not null,
    last_calculated timestamp with time zone not null,
    profit numeric,
    cash_balance numeric default 0.0 not null,
    cash_investment_value numeric default 0.0 not null,
    total_cash_deposits numeric default 0.0 not null
  );

-- Indexes
drop index if exists user_portfolio_history_latest_pkey;

create unique index user_portfolio_history_latest_pkey on public.user_portfolio_history_latest using btree (user_id);
