-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_monitor_status (
    id bigint primary key generated always as identity not null,
    user_id text not null,
    reason_codes text[],
    fraud_confidence_score integer,
    identity_confidence_score integer,
    data jsonb not null,
    created_time timestamp with time zone default now()
  );

-- Foreign Keys
alter table user_monitor_status
add constraint user_monitor_status_user_id_fkey foreign key (user_id) references users (id);

-- Row Level Security
alter table user_monitor_status enable row level security;

-- Indexes
drop index if exists user_monitor_status_pkey;

create unique index user_monitor_status_pkey on public.user_monitor_status using btree (id);

drop index if exists idx_user_monitor_status_user_id;

create index idx_user_monitor_status_user_id on public.user_monitor_status using btree (user_id, created_time desc);
