-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_contract_interactions (
    bet_group_id text,
    bet_id text,
    comment_id text,
    contract_id text not null,
    created_time timestamp with time zone default now() not null,
    feed_reasons text[],
    feed_type text,
    id bigint primary key generated always as identity not null,
    name text not null,
    user_id text not null
  );

-- Row Level Security
alter table user_contract_interactions enable row level security;

-- Indexes
drop index if exists user_contract_interactions_name_contract_id_user_id;

create index user_contract_interactions_name_contract_id_user_id on public.user_contract_interactions using btree (name, contract_id, user_id);

drop index if exists user_contract_interactions_pkey;

create unique index user_contract_interactions_pkey on public.user_contract_interactions using btree (id);

drop index if exists user_contract_interactions_user_id_created_time;

create index user_contract_interactions_user_id_created_time on public.user_contract_interactions using btree (user_id, created_time desc);
