-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_topics (
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  topic_embedding vector(1536) NOT NULL,
  topics text[] NOT NULL,
  user_id text PRIMARY KEY NOT NULL
);



-- Row Level Security
ALTER TABLE user_topics ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_topics;
CREATE POLICY "public read" ON user_topics FOR SELECT USING (true) ;

DROP POLICY IF EXISTS "public write access" ON user_topics;
CREATE POLICY "public write access" ON user_topics FOR INSERT WITH CHECK (true);

-- Indexes
DROP INDEX IF EXISTS user_topics_pkey;
CREATE UNIQUE INDEX user_topics_pkey ON public.user_topics USING btree (user_id);

