-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_view_events (
  ad_id text,
  comment_id text,
  contract_id text,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_view_events ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS user_view_events_contract_id_name_created_time;
CREATE INDEX user_view_events_contract_id_name_created_time ON public.user_view_events USING btree (contract_id, name, created_time DESC);
DROP INDEX IF EXISTS user_view_events_name_contract_id_user_id;
CREATE INDEX user_view_events_name_contract_id_user_id ON public.user_view_events USING btree (user_id, contract_id, name);
DROP INDEX IF EXISTS user_view_events_pkey;
CREATE UNIQUE INDEX user_view_events_pkey ON public.user_view_events USING btree (id);

