-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_quest_metrics (
    user_id text not null,
    score_id text not null,
    score_value numeric not null,
    idempotency_key text
  );

-- Policies
alter table user_quest_metrics enable row level security;

drop policy if exists "public read" on user_quest_metrics;

create policy "public read" on user_quest_metrics for
select
  using (true);

-- Indexes
drop index if exists user_quest_metrics_pkey;

create unique index user_quest_metrics_pkey on public.user_quest_metrics using btree (user_id, score_id);
