-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS users (
  balance numeric DEFAULT 0 NOT NULL,
  cash_balance numeric DEFAULT 0 NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  data jsonb NOT NULL,
  id text PRIMARY KEY DEFAULT random_alphanumeric(12) NOT NULL,
  name text NOT NULL,
  name_username_vector tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, (name || ' '::text) || username)) STORED,
  resolved_profit_adjustment numeric,
  spice_balance numeric DEFAULT 0 NOT NULL,
  total_cash_deposits numeric DEFAULT 0 NOT NULL,
  total_deposits numeric DEFAULT 0 NOT NULL,
  username text NOT NULL
);



-- Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON users;
CREATE POLICY "public read" ON users FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_referrals_idx;
CREATE INDEX user_referrals_idx ON public.users USING btree (((data ->> 'referredByUserId'::text))) WHERE ((data ->> 'referredByUserId'::text) IS NOT NULL);
DROP INDEX IF EXISTS user_username_idx;
CREATE INDEX user_username_idx ON public.users USING btree (username);
DROP INDEX IF EXISTS users_betting_streak_idx;
CREATE INDEX users_betting_streak_idx ON public.users USING btree ((((data -> 'currentBettingStreak'::text))::integer));
DROP INDEX IF EXISTS users_created_time;
CREATE INDEX users_created_time ON public.users USING btree (created_time DESC);
DROP INDEX IF EXISTS users_name_idx;
CREATE INDEX users_name_idx ON public.users USING btree (name);
DROP INDEX IF EXISTS users_pkey;
CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

