-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_topic_interests (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  group_ids_to_activity jsonb NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_topic_interests ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS user_topic_interests_created_time;
CREATE INDEX user_topic_interests_created_time ON public.user_topic_interests USING btree (user_id, created_time DESC);
DROP INDEX IF EXISTS user_topic_interests_pkey;
CREATE UNIQUE INDEX user_topic_interests_pkey ON public.user_topic_interests USING btree (id);

