-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_quest_metrics (
  idempotency_key text,
  score_id text NOT NULL,
  score_value numeric NOT NULL,
  user_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (user_id, score_id)
);



-- Row Level Security
ALTER TABLE user_quest_metrics ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_quest_metrics;
CREATE POLICY "public read" ON user_quest_metrics FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_quest_metrics_pkey;
CREATE UNIQUE INDEX user_quest_metrics_pkey ON public.user_quest_metrics USING btree (user_id, score_id);

