-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_bans (
    ban_type text not null,
    created_at timestamp with time zone default now() not null,
    created_by text,
    end_time timestamp with time zone,
    ended_at timestamp with time zone,
    ended_by text,
    id serial not null,
    reason text,
    user_id text not null
  );

-- Foreign Keys
alter table user_bans
add constraint user_bans_created_by_fkey foreign key (created_by) references users (id);

alter table user_bans
add constraint user_bans_ended_by_fkey foreign key (ended_by) references users (id);

alter table user_bans
add constraint user_bans_user_id_fkey foreign key (user_id) references users (id);

-- Indexes
drop index if exists user_bans_pkey;

create unique index user_bans_pkey on public.user_bans using btree (id);

drop index if exists user_bans_user_id_idx;

create index user_bans_user_id_idx on public.user_bans using btree (user_id);
