-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_notifications (
  data jsonb NOT NULL,
  notification_id text NOT NULL,
  user_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (user_id, notification_id)
);



-- Row Level Security
ALTER TABLE user_notifications ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_notifications;
CREATE POLICY "public read" ON user_notifications FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_notifications_notification_id;
CREATE INDEX user_notifications_notification_id ON public.user_notifications USING btree (notification_id, user_id);
DROP INDEX IF EXISTS user_notifications_pkey;
CREATE UNIQUE INDEX user_notifications_pkey ON public.user_notifications USING btree (user_id, notification_id);
DROP INDEX IF EXISTS user_notifications_user_id_created_time;
CREATE INDEX user_notifications_user_id_created_time ON public.user_notifications USING btree (user_id, (((data -> 'createdTime'::text))::bigint) DESC);

