-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_entitlements (
    enabled boolean default true not null,
    entitlement_id text not null,
    expires_time timestamp with time zone,
    granted_time timestamp with time zone default now() not null,
    user_id text not null,
    constraint primary key (user_id, entitlement_id)
  );

-- Indexes
drop index if exists user_entitlements_pkey;

create unique index user_entitlements_pkey on public.user_entitlements using btree (user_id, entitlement_id);
