-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_reactions (
    user_id text not null,
    reaction_id text default random_alphanumeric (12) not null,
    content_id text not null,
    content_type text not null,
    content_owner_id text not null,
    created_time timestamp with time zone default now() not null,
    reaction_type character varying(20)
  );

-- Policies
alter table user_reactions enable row level security;

drop policy if exists "public read" on user_reactions;

create policy "public read" on user_reactions for
select
  using (true);

-- Indexes
drop index if exists user_reactions_pkey;

create unique index user_reactions_pkey on public.user_reactions using btree (user_id, reaction_id);

drop index if exists user_reactions_content_id_raw;

create index user_reactions_content_id_raw on public.user_reactions using btree (content_id);
