-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_reactions (
  content_id text NOT NULL,
  content_owner_id text NOT NULL,
  content_type text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  reaction_id text DEFAULT random_alphanumeric(12) NOT NULL,
  reaction_type text DEFAULT 'like'::text NOT NULL,
  user_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (user_id, reaction_id)
);



-- Row Level Security
ALTER TABLE user_reactions ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_reactions;
CREATE POLICY "public read" ON user_reactions FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_reactions_content_id_raw;
CREATE INDEX user_reactions_content_id_raw ON public.user_reactions USING btree (content_id);
DROP INDEX IF EXISTS user_reactions_pkey;
CREATE UNIQUE INDEX user_reactions_pkey ON public.user_reactions USING btree (user_id, reaction_id);

