-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_follows (
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  follow_id text NOT NULL,
  user_id text NOT NULL,
  CONSTRAINT PRIMARY KEY (user_id, follow_id)
);



-- Row Level Security
ALTER TABLE user_follows ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_follows;
CREATE POLICY "public read" ON user_follows FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_follows_pkey;
CREATE UNIQUE INDEX user_follows_pkey ON public.user_follows USING btree (user_id, follow_id);

