-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_events (
  ad_id text,
  comment_id text,
  contract_id text,
  data jsonb NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  ts timestamp with time zone DEFAULT now() NOT NULL,
  user_id text
);



-- Row Level Security
ALTER TABLE user_events ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "self and admin read" ON user_events;
CREATE POLICY "self and admin read" ON user_events FOR SELECT USING (((user_id = firebase_uid()) OR is_admin(firebase_uid()))) ;

DROP POLICY IF EXISTS "user can insert" ON user_events;
CREATE POLICY "user can insert" ON user_events FOR INSERT WITH CHECK (true);

-- Indexes
DROP INDEX IF EXISTS user_events_pkey;
CREATE UNIQUE INDEX user_events_pkey ON public.user_events USING btree (id);
DROP INDEX IF EXISTS user_events_ts;
CREATE INDEX user_events_ts ON public.user_events USING btree (ts DESC);

