-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_comment_view_events (
  comment_id text NOT NULL,
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_comment_view_events ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS user_comment_view_events_pkey;
CREATE UNIQUE INDEX user_comment_view_events_pkey ON public.user_comment_view_events USING btree (id);
DROP INDEX IF EXISTS user_comment_view_events_user_id_created_time;
CREATE INDEX user_comment_view_events_user_id_created_time ON public.user_comment_view_events USING btree (user_id, created_time DESC);

