-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_embeddings (
  contract_view_embedding vector(1536),
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  disinterest_embedding vector(1536),
  interest_embedding vector(1536) NOT NULL,
  user_id text PRIMARY KEY NOT NULL
);



-- Row Level Security
ALTER TABLE user_embeddings ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "admin write access" ON user_embeddings;
CREATE POLICY "admin write access" ON user_embeddings FOR ALL TO service_role ;

DROP POLICY IF EXISTS "public read" ON user_embeddings;
CREATE POLICY "public read" ON user_embeddings FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_embeddings_pkey;
CREATE UNIQUE INDEX user_embeddings_pkey ON public.user_embeddings USING btree (user_id);

