-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_view_events (
    ad_id text,
    comment_id text,
    contract_id text,
    created_time timestamp with time zone default now() not null,
    id bigint primary key generated always as identity not null,
    name text not null,
    user_id text not null
  );

-- Row Level Security
alter table user_view_events enable row level security;

-- Indexes
drop index if exists user_view_events_contract_id_name_created_time;

create index user_view_events_contract_id_name_created_time on public.user_view_events using btree (contract_id, name, created_time desc);

drop index if exists user_view_events_name_contract_id_user_id;

create index user_view_events_name_contract_id_user_id on public.user_view_events using btree (user_id, contract_id, name);

drop index if exists user_view_events_pkey;

create unique index user_view_events_pkey on public.user_view_events using btree (id);
