-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_embeddings (
    contract_view_embedding vector (1536),
    created_at timestamp without time zone default now() not null,
    disinterest_embedding vector (1536),
    interest_embedding vector (1536) not null,
    user_id text primary key not null
  );

-- Row Level Security
alter table user_embeddings enable row level security;

-- Policies
drop policy if exists "admin write access" on user_embeddings;

create policy "admin write access" on user_embeddings for all to service_role;

drop policy if exists "public read" on user_embeddings;

create policy "public read" on user_embeddings for
select
  using (true);

-- Indexes
drop index if exists user_embeddings_pkey;

create unique index user_embeddings_pkey on public.user_embeddings using btree (user_id);
