-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_follows (
    created_time timestamp with time zone default now() not null,
    follow_id text not null,
    user_id text not null,
    primary key (user_id, follow_id)
  );

-- Row Level Security
alter table user_follows enable row level security;

-- Policies
drop policy if exists "public read" on user_follows;

create policy "public read" on user_follows for
select
  using (true);

-- Indexes
drop index if exists user_follows_pkey;

create unique index user_follows_pkey on public.user_follows using btree (user_id, follow_id);
