-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_portfolio_history_latest (
  balance numeric NOT NULL,
  cash_balance numeric DEFAULT 0.0 NOT NULL,
  cash_investment_value numeric DEFAULT 0.0 NOT NULL,
  investment_value numeric NOT NULL,
  last_calculated timestamp with time zone NOT NULL,
  loan_total numeric,
  profit numeric,
  spice_balance numeric DEFAULT 0.0 NOT NULL,
  total_cash_deposits numeric DEFAULT 0.0 NOT NULL,
  total_deposits numeric NOT NULL,
  ts timestamp without time zone NOT NULL,
  user_id text PRIMARY KEY NOT NULL
);



-- Indexes
DROP INDEX IF EXISTS user_portfolio_history_latest_pkey;
CREATE UNIQUE INDEX user_portfolio_history_latest_pkey ON public.user_portfolio_history_latest USING btree (user_id);

