-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_disinterests (
  comment_id text,
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  creator_id text NOT NULL,
  feed_id bigint,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_disinterests ENABLE ROW LEVEL SECURITY;
-- Policies
DROP POLICY IF EXISTS "public read" ON user_disinterests;
CREATE POLICY "public read" ON user_disinterests FOR SELECT USING (true) ;

-- Indexes
DROP INDEX IF EXISTS user_disinterests_pkey;
CREATE UNIQUE INDEX user_disinterests_pkey ON public.user_disinterests USING btree (id);
DROP INDEX IF EXISTS user_disinterests_user_id;
CREATE INDEX user_disinterests_user_id ON public.user_disinterests USING btree (user_id);
DROP INDEX IF EXISTS user_disinterests_user_id_contract_id;
CREATE INDEX user_disinterests_user_id_contract_id ON public.user_disinterests USING btree (user_id, contract_id);

