-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_contract_interactions (
  bet_group_id text,
  bet_id text,
  comment_id text,
  contract_id text NOT NULL,
  created_time timestamp with time zone DEFAULT now() NOT NULL,
  feed_reasons text[],
  feed_type text,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  user_id text NOT NULL
);



-- Row Level Security
ALTER TABLE user_contract_interactions ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS user_contract_interactions_name_contract_id_user_id;
CREATE INDEX user_contract_interactions_name_contract_id_user_id ON public.user_contract_interactions USING btree (name, contract_id, user_id);
DROP INDEX IF EXISTS user_contract_interactions_pkey;
CREATE UNIQUE INDEX user_contract_interactions_pkey ON public.user_contract_interactions USING btree (id);
DROP INDEX IF EXISTS user_contract_interactions_user_id_created_time;
CREATE INDEX user_contract_interactions_user_id_created_time ON public.user_contract_interactions USING btree (user_id, created_time DESC);

