-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_contract_metrics (
    user_id text not null,
    contract_id text not null,
    data jsonb not null,
    has_yes_shares boolean,
    has_no_shares boolean,
    total_shares_yes numeric,
    total_shares_no numeric,
    profit numeric,
    has_shares boolean,
    answer_id text,
    id bigint not null,
    profit_adjustment numeric
  );

-- Policies
alter table user_contract_metrics enable row level security;

drop policy if exists "public read" on user_contract_metrics;

create policy "public read" on user_contract_metrics for
select
  using (true);

drop policy if exists "read for admin" on user_contract_metrics;

create policy "read for admin" on user_contract_metrics for
select
  to service_role using (true);

-- Indexes
drop index if exists user_contract_metrics_pkey;

create unique index user_contract_metrics_pkey on public.user_contract_metrics using btree (id);

drop index if exists contract_metrics_answer_id;

create index contract_metrics_answer_id on public.user_contract_metrics using btree (contract_id, answer_id);

drop index if exists idx_user_contract_metrics_contract_profit;

create index idx_user_contract_metrics_contract_profit on public.user_contract_metrics using btree (contract_id, profit);

drop index if exists unique_user_contract_answer;

create unique index unique_user_contract_answer on public.user_contract_metrics using btree (
  user_id,
  contract_id,
  coalesce(answer_id, ''::text)
);

drop index if exists user_contract_metrics_recent_bets;

create index user_contract_metrics_recent_bets on public.user_contract_metrics using btree (
  user_id,
  (((data -> 'lastBetTime'::text))::bigint) desc
);
