-- This file is autogenerated from regen-schema.ts

CREATE TABLE IF NOT EXISTS user_monitor_status (
  created_time timestamp with time zone DEFAULT now(),
  data jsonb NOT NULL,
  fraud_confidence_score integer,
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  identity_confidence_score integer,
  reason_codes text[],
  user_id text NOT NULL
);

-- Foreign Keys
ALTER TABLE user_monitor_status ADD CONSTRAINT user_monitor_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);


-- Row Level Security
ALTER TABLE user_monitor_status ENABLE ROW LEVEL SECURITY;
-- Indexes
DROP INDEX IF EXISTS idx_user_monitor_status_user_id;
CREATE INDEX idx_user_monitor_status_user_id ON public.user_monitor_status USING btree (user_id, created_time DESC);
DROP INDEX IF EXISTS user_monitor_status_pkey;
CREATE UNIQUE INDEX user_monitor_status_pkey ON public.user_monitor_status USING btree (id);

