-- This file is autogenerated from regen-schema.ts
create or replace view
  final_pp_balances as
select
  txns.from_id as user_id,
  txns.amount
from
  txns
where
  (
    (txns.category = 'CONSUME_SPICE'::text)
    and (
      ((txns.data -> 'data'::text) ->> 'isLast'::text) is not null
    )
  );

create or replace view
  group_role as
select
  gm.member_id,
  gp.id as group_id,
  gp.name as group_name,
  gp.slug as group_slug,
  gp.creator_id,
  gp.total_members,
  users.name,
  users.username,
  (users.data ->> 'avatarUrl'::text) as avatar_url,
  gm.role,
  ts_to_millis (gm.created_time) as createdtime,
  gp.privacy_status
from
  (
    (
      group_members gm
      join groups gp on ((gp.id = gm.group_id))
    )
    join users on ((users.id = gm.member_id))
  );

create or replace view
  user_league_info as
select
  leagues.season,
  leagues.division,
  leagues.cohort,
  leagues.user_id,
  leagues.mana_earned,
  leagues.created_time,
  leagues.mana_earned_breakdown,
  leagues.rank_snapshot,
  (
    row_number() over (
      partition by
        leagues.season,
        leagues.division,
        leagues.cohort
      order by
        leagues.mana_earned desc
    )
  )::integer as rank
from
  leagues;

create or replace view
  user_referrals_profit as
select
  subquery.id,
  subquery.total_referrals,
  subquery.total_referred_profit,
  subquery.total_referred_cash_profit,
  rank() over (
    order by
      subquery.total_referrals desc
  ) as rank
from
  (
    select
      referrer.id,
      count(*) as total_referrals,
      sum(
        (
          (
            (uphl.balance + uphl.spice_balance) + uphl.investment_value
          ) - uphl.total_deposits
        )
      ) as total_referred_profit,
      sum(
        (
          (uphl.cash_balance + uphl.cash_investment_value) - uphl.total_cash_deposits
        )
      ) as total_referred_cash_profit
    from
      (
        (
          users referred
          join users referrer on (
            (
              referrer.id = (referred.data ->> 'referredByUserId'::text)
            )
          )
        )
        join user_portfolio_history_latest uphl on ((referred.id = uphl.user_id))
      )
    where
      (
        (referred.data ->> 'referredByUserId'::text) is not null
      )
    group by
      referrer.id
  ) subquery
order by
  subquery.total_referrals desc;
