-- This file is autogenerated from regen-schema.ts
create table if not exists
  votes (
    contract_id text not null,
    created_time timestamp with time zone default now() not null,
    id text not null,
    user_id text not null,
    constraint primary key (id, contract_id, user_id)
  );

-- Row Level Security
alter table votes enable row level security;

-- Policies
drop policy if exists "Enable read access for all users" on votes;

create policy "Enable read access for all users" on votes for
select
  using (true);

-- Indexes
drop index if exists votes_pkey;

create unique index votes_pkey on public.votes using btree (id, contract_id, user_id);
