-- This file is autogenerated from regen-schema.ts
create table if not exists
  weekly_update (
    contract_metrics json not null,
    created_time timestamp with time zone default now() not null,
    id text primary key default random_alphanumeric (12) not null,
    profit numeric not null,
    range_end date not null,
    user_id text not null
  );

-- Foreign Keys
alter table weekly_update
add constraint weekly_update_user_id_fkey foreign key (user_id) references users (id);

-- Row Level Security
alter table weekly_update enable row level security;

-- Policies
drop policy if exists "public read" on weekly_update;

create policy "public read" on weekly_update for
select
  using (true);

-- Indexes
drop index if exists weekly_update_pkey;

create unique index weekly_update_pkey on public.weekly_update using btree (id);
