const adjectives = [
  'unlucky',
  'lucky',
  'risky',
  'bullish',
  'bearish',
  'diversified',
  'speculative',
  'predictive',
  'calculated',
  'fortuitous',
  'serendipitous',
  'prophetic',
  'futuristic',
  'clairvoyant',
  'prescient',
  'auspicious',
  'profitable',
  'farsighted',
  'uncanny',
  'astrological',
  'astute',
  'extrapolative',
  'optimistic',
  'pessimistic',
  'mystical',
  'psychic',
  'balanced',
  'hedged',
  'leveraged',
  'shrewd',
  'savvy',
  'canny',
  'prudent',
  'fortunate',
  'enigmatic',
  'volatile',
  'aggressive',
  'contrarian',
  'adventurous',
  'perceptive',
  'unerring',
  'intrepid',
  'proactive',
  'opportunistic',
  'tenacious',
  'fierce',
  'exponential',
  'visionary',
  'innovative',
  'disruptive',
  'quirky',
  'stellar',
  'futuristic',
  'cryptic',
  'mystic',
  'galactic',
  'quantum',
  'cunning',
  'zealous',
  'wily',
  'hyperactive',
  'dauntless',
  'supersonic',
  'giga',
  'iridescent',
  'audacious',
  'mantic',
  'unpredictable',
  'calibrated',
  'sage',
  'based',
  'bayesian',
  'degenerate',
  'shy',
]

const animals = [
  'prophets',
  'seers',
  'augurs',
  'oracles',
  'diviners',
  'sibyls',
  'druids',
  'shamans',
  'clairvoyants',
  'predictors',
  'witches',
  'wizards',
  'sorcerers',
  'conjurers',
  'magicians',
  'enchanters',
  'necromancers',
  'warlocks',
  'alchemists',
  'illusionists',
  'charmers',
  'mystics',
  'telepaths',
  'psychics',
  'soothsayers',
  'dreamers',
  'prodigies',
  'jinxes',
  'totems',
  'ogres',
  'griffins',
  'sphinxes',
  'goblins',
  'nymphs',
  'pixies',
  'elves',
  'genies',
  'banshees',
  'centaurs',
  'werewolves',
  'basilisks',
  'chimeras',
  'gargoyles',
  'hydras',
  'krakens',
  'minotaurs',
  'manticores',
  'pegasus',
  'phoenixes',
  'unicorns',
  'yetis',
  'zombies',
  'leviathans',
  'salamanders',
  'thunderbirds',
  'valkyries',
  'poltergeists',
  'wraiths',
  'leprechauns',
  'sirens',
  'mermaids',
  'harpies',
  'medusas',
  'cyclopes',
  'dragons',
  'hobgoblins',
  'wererats',
  'gnomes',
  'boggarts',
  'banshees',
  'brownies',
  'faeries',
  'gremlins',
  'wights',
  'sprites',
  'cranes',
  'rats',
  'ravens',
  'owls',
  'bulls',
  'bears',
  'golems',
  'neanderthals',
  'foxes',
  'hedgehogs',
]

export const getRandomAdjectiveAnimal = () => {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)]
  const animal = animals[Math.floor(Math.random() * animals.length)]
  return `${adj}-${animal}`
}

export const genNewAdjectiveAnimal = (ids: Set<string>) => {
  let adjAnimal = getRandomAdjectiveAnimal()
  while (ids.has(adjAnimal)) {
    adjAnimal = getRandomAdjectiveAnimal()
  }
  return adjAnimal
}

export const toLabel = (adjAnimal: string) => {
  return adjAnimal
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(' ')
}
