const adjectives = [
  'Unlucky',
  'Lucky',
  'Risky',
  'Bullish',
  'Bearish',
  'Diversified',
  'Speculative',
  'Predictive',
  'Calculated',
  'Fortuitous',
  'Serendipitous',
  'Prophetic',
  'Futuristic',
  'Clairvoyant',
  'Prescient',
  'Auspicious',
  'Profitable',
  'Farsighted',
  'Uncanny',
  'Astrological',
  'Astute',
  'Extrapolative',
  'Optimistic',
  'Pessimistic',
  'Mystical',
  'Psychic',
  'Balanced',
  'Hedged',
  'Leveraged',
  'Shrewd',
  'Savvy',
  'Canny',
  'Prudent',
  'Fortunate',
  'Enigmatic',
  'Volatile',
  'Aggressive',
  'Contrarian',
  'Adventurous',
  'Perceptive',
  'Unerring',
  'Intrepid',
  'Proactive',
  'Opportunistic',
  'Tenacious',
  'Fierce',
  'Exponential',
  'Visionary',
  'Innovative',
  'Disruptive',
  'Quirky',
  'Stellar',
  'Futuristic',
  'Cryptic',
  'Mystic',
  'Galactic',
  'Quantum',
  'Cunning',
  'Zealous',
  'Wily',
  'Hyperactive',
  'Dauntless',
  'Supersonic',
  'Giga',
  'Iridescent',
  'Audacious',
  'Mantic',
  'Unpredictable',
  'Calibrated',
  'Sage',
  'Based',
  'Bayesian',
  'Degenerate',
  'Shy',
]

const animals = [
  'Prophets',
  'Seers',
  'Augurs',
  'Oracles',
  'Diviners',
  'Sibyls',
  'Druids',
  'Shamans',
  'Clairvoyants',
  'Predictors',
  'Witches',
  'Wizards',
  'Sorcerers',
  'Conjurers',
  'Magicians',
  'Enchanters',
  'Necromancers',
  'Warlocks',
  'Alchemists',
  'Illusionists',
  'Charmers',
  'Mystics',
  'Telepaths',
  'Psychics',
  'Soothsayers',
  'Dreamers',
  'Prodigies',
  'Jinxes',
  'Totems',
  'Ogres',
  'Griffins',
  'Sphinxes',
  'Goblins',
  'Nymphs',
  'Pixies',
  'Elves',
  'Genies',
  'Banshees',
  'Centaurs',
  'Werewolves',
  'Basilisks',
  'Chimeras',
  'Gargoyles',
  'Hydras',
  'Krakens',
  'Minotaurs',
  'Manticores',
  'Pegasus',
  'Phoenixes',
  'Unicorns',
  'Yetis',
  'Zombies',
  'Leviathans',
  'Salamanders',
  'Thunderbirds',
  'Valkyries',
  'Poltergeists',
  'Wraiths',
  'Leprechauns',
  'Sirens',
  'Mermaids',
  'Harpies',
  'Medusas',
  'Cyclopes',
  'Dragons',
  'Hobgoblins',
  'Wererats',
  'Gnomes',
  'Boggarts',
  'Banshees',
  'Brownies',
  'Faeries',
  'Gremlins',
  'Wights',
  'Sprites',
  'Cranes',
  'Rats',
  'Ravens',
  'Owls',
  'Bulls',
  'Bears',
  'Golems',
  'Neanderthals',
  'Phoenixes',
  'Dragons',
]

export const getRandomAdjectiveAnimal = () => {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)]
  const animal = animals[Math.floor(Math.random() * animals.length)]
  return `${adj}-${animal}`
}

export const genNewAdjectiveAnimal = (ids: Set<string>) => {
  let adjAnimal = getRandomAdjectiveAnimal()
  while (ids.has(adjAnimal)) {
    adjAnimal = getRandomAdjectiveAnimal()
  }
  return adjAnimal
}

export const toLabel = (adjAnimal: string) => {
  return adjAnimal
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(' ')
}
