name: Merge main into main2 on every commit
on:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> main2
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main2
          github_token: ${{ github.token }}
