name: Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - 'common/**'
  pull_request:
    branches: [main]
    paths:
      - 'common/**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: 'common/yarn.lock'
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        working-directory: ./common
      - name: Run lint
        run: yarn lint
      - name: Run unit tests
        run: yarn test
        working-directory: ./common
